### ISSUE TITLE
Upgrade validation layers to use VK_EXT_debug_utils

### ISSUE THREAD

**Issue by kondrak** [Overv/VulkanTutorial#102]
According to Vulkan specs, `VK_EXT_debug_utils` is the "proper" extension to use for validation layers and `VK_EXT_debug_report` will no longer be developed further. I think it would be a good idea to mention that in the tutorial and replace current implementation to make use of the new structures.

**Comment by Overv** [comment]
Thanks, I will look into this.

**Comment by lewa-j** [comment]
Almost everything that needs to be done is to replace VkDebugUtilsMessengerEXT to VkDebugReportCallbackEXT and vkCreateDebugUtilsMessengerEXT to vkCreateDebugReportCallbackEXT.

**Comment by Overv** [comment]
I have modified the code from the depth buffering chapter to use `VK_EXT_debug_utils`, but it seems that it fails to capture many errors that `VK_EXT_debug_report` *does* capture. For example, it does not warn me about not deleting all the resources that I've commented out in the cleanup function:

https://gist.github.com/Overv/337b72f38460114141680db28ecf09c2

Am I doing something wrong?

**Comment by kondrak** [comment]
https://gist.github.com/Overv/337b72f38460114141680db28ecf09c2#file-main-cpp-L376

You're using the WARNING bit twice, so you're not catching ERROR. :-)

**Comment by Overv** [comment]
Hah, you're right. Thanks for spotting that so quickly.
