### ISSUE TITLE
Rust version

### ISSUE THREAD

**Issue by bwasty** [Overv/VulkanTutorial#107]
Hi,
I've started working on a Rust version of the tutorial: [vulkan-tutorial-rs](https://github.com/bwasty/vulkan-tutorial-rs).
After reading through #37, I think it would be easiest to keep it separate, but perhaps add a link somewhere on the main tutorial?

**Comment by Overv** [comment]
Very nice! I think keeping it separate is a good idea, but I can certainly link to it from the sidebar and introduction. Do you plan to host it on a website somewhere or should I link to the GitHub repository?

**Comment by bwasty** [comment]
That would be great! I'll keep it on GitHub (perhaps GitHub Pages eventually, but a link to the repo should be fine).

**Comment by Overv** [comment]
I've added a link in the introduction and sidebar now :)
