### ISSUE TITLE
Remove DeviceLayers during LogicalDevice Creation

### ISSUE THREAD

**Issue by ClemensGerstung** [Overv/VulkanTutorial#109]
Just a minor detail: [DeviceLayers are deprecated](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#extended-functionality-device-layer-deprecation)
To quote the spec: 
> The ppEnabledLayerNames and enabledLayerCount members of VkDeviceCreateInfo are deprecated and their values must be ignored by implementations. However, for compatibility, only an empty list of layers or a list that exactly matches the sequence enabled at instance creation time are valid, and validation layers should issue diagnostics for other cases.

So you can save a few lines of code in your example [here](https://github.com/Overv/VulkanTutorial/blob/master/03_Drawing_a_triangle/00_Setup/04_Logical_device_and_queues.md).

the layer part might be just:
```c++
createInfo.enabledLayerCount = 0;
createInfo.ppEnabledLayerNames = nullptr;
```

**Comment by Overv** [comment]
This is taken into account as of 5cf25e3fb1f31eaf3cc481ef53c51eeebd13f89a.
