### ISSUE TITLE
Expanded list of must reads

### ISSUE THREAD

**Issue by salamanderrake** [Overv/VulkanTutorial#110]
Two must reads that should be first on your list.
[Ray Tracing in One Weekend ](https://github.com/petershirley/raytracinginoneweekend/releases/)
[Ray Tracing: The Next Week ](https://github.com/petershirley/raytracingthenextweek/releases/)

An online book that was once in print but was put up online only because the authors didn't like the quality of the printers work.
Online book [Physically Based Rendering](http://www.pbr-book.org/)

Pretty much a complete list of must read books
List of books on Eric Haine's [Real Time Rendering ](http://www.realtimerendering.com/#books-small-table) site 

Pixar in a box:  Kahn Academy
[Rendering]{https://www.khanacademy.org/partner-content/pixar/rendering)
[Their complete list](https://www.khanacademy.org/partner-content/pixar/)

[vkQuake](https://github.com/Novum/vkQuake)
[vkDOOM3](https://github.com/DustinHLand/vkDOOM3)

**Comment by Overv** [comment]
I would probably include the links organized as such:

* Basic raytracing: https://github.com/petershirley/raytracinginoneweekend
* More in-depth lighting and shading through writing a path tracer: http://www.pbr-book.org/
* Other great resources on computer graphics: http://www.realtimerendering.com/#books-small-table
* Examples of Vulkan being put into practice to make an engine:
    * https://github.com/Novum/vkQuake
    * https://github.com/DustinHLand/vkDOOM3

What do you think?

**Comment by salamanderrake** [comment]
Sure thats great, sounds a lot better then how I worded it.
