### ISSUE TITLE
Translation in French

### ISSUE THREAD

**Issue by QuartzIsCheap** [Overv/VulkanTutorial#111]
Hello!
Your tutorial is awesome. But as a French reader, even though I speak English quite well, it's hard to integrate the concepts of such a difficult topic, and the language just makes it even harder. So I translated it in French.
You can check the fork I did [here](https://github.com/QuartzIsCheap/VulkanTutorial), I put all the translated files in the "fr" folder.
Are you even interested in this translation? If yes, then should I do a pull request?

**Comment by SoulsD** [comment]
Hello,

As a French myself, I would be happy to help and review your work if needed.
I think such addition to one of the best vulkan tutorial out there can only be positive.

Regards,

**Comment by MacGamerFR** [comment]
Hi,
If help needed for review, I'm here as well :)

**Comment by QuartzIsCheap** [comment]
Hi, thanks for the interest!

Before anything, I'm not sure about the translation of the technical vocabulary. "queue family" translates well into "familles de queues", but "device" can't be translated into "dispositif" without loosing it's meaning. Same goes for "compute", which I translated into "calcul", but I find it a bit weird. I chose to translate what can reasonably be translated. But I think it also makes sense not to translate any of the words corresponding to the main Vulkan concepts. What do you think about that?

Another thing, is the current "fr" folder ok to you @Overv?

And I'd be glad if you could review it @SoulsD! How should we do that then?

**Comment by Overv** [comment]
I agree with @MacGamerFR, make sure that concepts are still easy to google. The `fr` folder is fine. I may need to move the existing chapters to a folder called `en`, but we'll see about that later.

**Comment by QuartzIsCheap** [comment]
That's a very good point I didn't consider. I'll change that.

**Comment by Overv** [comment]
@SoulsD Do keep in mind that the structure of the repository is basically constrained by what the CMS daux.io requires: http://daux.io/Features/Multilanguage

**Comment by QuartzIsCheap** [comment]
Hi! I'd say my part is done. How do you want to review the files?

**Comment by QuartzIsCheap** [comment]
Hi! If I understand correctly, the thread went silent because you're working on a way to redesign the site... Right?

**Comment by SoulsD** [comment]
Hello,

Sorry, I thought I had replied already. And time goes fast apparently.
With the information @Overv gave about the CMS, it is apparently unnecessary to do that.

I started reviewing your repository with the translated files but since there is a bit of content it is taking quite some time.

I'll be in vacation starting tomorrow and I already planned to finish that review during that time.
What I manage to find as an acceptable solution is that I will fork your repository and do a PR with all the comments/suggestions as well as corrections so it should be easy for you to review.

**Comment by QuartzIsCheap** [comment]
Hello,

The PR solution seems to be the cleanest way. I hope I didn't make too many mistakes :)

Anyways, happy holidays!

**Comment by DragonJoker** [comment]
Great news, this translation.
I will help reviewing too, and if I have spare time I'll help you translating it.

**Comment by feyleth** [comment]
hello,

I have take the translation of @QuartzIsCheap and i update it, I also allowed the generation of html pages and ebooks

you can check this at this depo [here](https://github.com/feyleth/VulkanTutorial)

if you want, I can do pull request

**Comment by MacGamerFR** [comment]
It would have been easier for reviewers to help with translation in the @QuartzIsCheap 's repo.
But considering he doesn't have any activity since several months...

I will look at your translation and review it on my spare time.

**Comment by QuartzIsCheap** [comment]
Hello,
I'm very sorry for my absence, I have been more busy than I expected. I'm in holidays for a while now, so I'll be available.

I'll give myself a week to rephrase the translation I did, and make it ready for a final pull request. Thank you @MacGamerFR for the reviews.

I have no idea how the pdf generation works though, so I'm interested in that @feyleth .

**Comment by QuartzIsCheap** [comment]
Hi everyone! I'd say the translation is done! Thanks for the help!
