### ISSUE TITLE
Using std::copy instead of memcpy

### ISSUE THREAD

**Issue by MacGamerFR** [Overv/VulkanTutorial#115]
Hello,
I've been wondering, why not using `std::copy` instead of memcpy ?
It offer some advantages and as long as you are using C++ for the tutorial, it should not differ from the actual implementation.

I got the uniforms update right with it :
```cpp
auto data = static_cast<UniformBufferObject*>(device.mapMemory(uniformBuffersMemory[currentImage], /*offset*/ 0, sizeof(ubo)));
{
	std::copy(&ubo, (&ubo)+1, data);
}
device.unmapMemory(uniformBuffersMemory[currentImage]);
```
(sorry I'm using the vulkanhpp header)
It's likely not the best example, but you got it.

Cheers

**Comment by Overv** [comment]
I could change it, but the syntax is a bit unwieldy in this case. What advantages would it have here?
