### ISSUE TITLE
Using (or suggesting why not) the vulkan.hpp C++ API?

### ISSUE THREAD

**Issue by paulreimer** [Overv/VulkanTutorial#116]
Love the tutorial -- perhaps one of the best online tutorials I've ever read, it made a substantial subject quite easy to understand and easy to reference later.

I appreciate that it is using C++17, I think that makes the Vulkan-specific parts easier to focus on. Is there a specific reason not to use the official C++ Vulkan wrapper?
https://github.com/KhronosGroup/Vulkan-Hpp

To catch at compile-time some of the possible C API pitfalls noted here:
> https://developer.nvidia.com/open-source-vulkan-c-api
- initialization of ci.sType using wrong enum values
- uninitialized data fields (e.g. missing initialization of ci.mipLevels)
- use of invalid bits for ci.flags (no type-safety for bits)
- use of incorrect enums for fields (no type-safety for enums)

As well as other positive features such as namespacing, enum classes, accept `vector` / `string` instead of raw buffer pointers, etc.

Even adding a note that the alternative C++ wrapper exists, but e.g. it is not used here for simplicity, or because C interop is easier, or in the pursuit of minimal dependencies etc could help me decide whether to use it for myself, too.

**Comment by Overv** [comment]
I should have definitely added a mention of the C++ API earlier and have done so now. There are a few reasons for the tutorial not using it right now:

* It was written before they existed
* Easier to follow along for programmers using other languages
* Experience with the base API before abstracting things

You definitely make very good points about classes of errors being prevented and it just fitting more nicely into an existing C++ code base, and I would recommend using the bindings for a serious project. However, for this tutorial I think that using the C API makes more sense.

**Comment by paulreimer** [comment]
OK thank you, that is clear!
