### ISSUE TITLE
Typo in Swap Chain Chapter

### ISSUE THREAD

**Issue by hydroo** [Overv/VulkanTutorial#117]
I found a tiny mistake in the swap chain chapter.

```
There is actually one more small things that need to be decided upon, but it's
so simple that it's not really worth creating separate functions for them. The
first one is the number of images
```
in `03_Drawing_a_triangle/01_Presentation/01_Swap_chain.md`

The first sentence needs to be either "two" instead of "one", or the plural is wrong.
What's slightly confusing is that the second sentence talks about the "first one", but I can't find a second one.

Best, Ronny

P.S.: If you clarify this, I can create a PR, too.

**Comment by Overv** [comment]
Oh yeah, that must have been a leftover from a draft version of that chapter. There is indeed only *one more thing* and I've updated the text to reflect that.
