### ISSUE TITLE
Adding helper function for filling buffers

### ISSUE THREAD

**Issue by MacGamerFR** [Overv/VulkanTutorial#122]
Hi,
There are several use of the same little piece of code in the case of filling buffer with data, like for staging vertex buffers, uniform buffers and image buffers...
```cpp
void* data;
vkMapMemory(device, stagingBufferMemory, 0, size, 0, &data);
    memcpy(data, pixels, static_cast<size_t>(size));
vkUnmapMemory(device, stagingBufferMemory);
```

Why not creating a little helper for that matter ? It could look like this:
```cpp
void fillBuffer(VkDeviceMemory& memory, const void* dataToCopy, VkDeviceSize size) {
	void* data;
	VkMapMemory(device, memory, /*offset*/ 0, size, 0, &data);
		std::memcpy(data, dataToCopy, static_cast<size_t>(size));
	VkUnmapMemory(device, memory);
}
```

**Comment by Overv** [comment]
Sure, it's possible to create a helper for things like this but I don't think it's worth mentioning in the tutorial.

**Comment by MacGamerFR** [comment]
The main reason for me is reducing code duplication, and it's quite convenient.
But if it's not worth mentioning, I'll just close the issue. Thank you.

**Comment by Overv** [comment]
I didn't intend to come across as rude but instructions about code style are somewhat outside the scope of the tutorial, which is also why the code is one big C++ file. It's more about understanding the Vulkan API and interacting with it.

**Comment by MacGamerFR** [comment]
I get your point, no problem.
By the way, the tutorial is great, you do a great job.
