### ISSUE TITLE
add an exit program key event

### ISSUE THREAD

**Issue by madjestic** [Overv/VulkanTutorial#124]
Hello, 

At the moment there's no keyboard event handling in place to close the application by pressing a key.  If a user is not using a WM, such as X11 on GNU/Linux, running the tutorial application as is can make it impossible to exit or abort the application, effectively hanging the system. 

It is very trivial to fix, considering we are already using glfw to handle the application window:

```cpp
void mainLoop() {
        while (!glfwWindowShouldClose(window)) {
          processInput(window);
          glfwPollEvents();
        }
    }

...

void processInput(GLFWwindow *window)
{
  if(glfwGetKey(window, GLFW_KEY_ESCAPE) == GLFW_PRESS)
    glfwSetWindowShouldClose(window, true);
}
```  

With this little fix a user can close the window even if no X11 is running.

Cheers,
Vlad

**Comment by MacGamerFR** [comment]
Could it be a hint for how to deal with vkDisplayKHR ?

**Comment by Overv** [comment]
@MacGamerFR That is a good idea, it should probably be more highlighted how a window is not necessary with Vulkan in general.

**Comment by Overv** [comment]
I've mentioned in the overview that it is possible to render without a window on certain platforms. Since one would not use GLFW in that case, the requirement for other types of lifecycle handling is implicit.

**Comment by Overv** [comment]
Ah, right, Optimus...

Is this an alright solution?

```
void initWindow() {
    glfwInit();

    glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);

    window = glfwCreateWindow(WIDTH, HEIGHT, "Vulkan", nullptr, nullptr);
    glfwSetWindowUserPointer(window, this);
    glfwSetFramebufferSizeCallback(window, framebufferResizeCallback);
    glfwSetKeyCallback(window, keyCallback);
}

static void framebufferResizeCallback(GLFWwindow* window, int width, int height) {
    auto app = reinterpret_cast<HelloTriangleApplication*>(glfwGetWindowUserPointer(window));
    app->framebufferResized = true;
}

static void keyCallback(GLFWwindow* window, int key, int scanCode, int action, int modifiers) {
    if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS) {
        glfwSetWindowShouldClose(window, GLFW_TRUE);
    }
}
```

**Comment by madjestic** [comment]
It looks like it's working, thanks!
