### ISSUE TITLE
Spec is becoming orientation agnostic for texture coordinates

### ISSUE THREAD

**Issue by francoisbertelatschrodinger** [Overv/VulkanTutorial#127]
Hello,

as you can see in a comment of the following Vulkan spec issue https://github.com/KhronosGroup/Vulkan-Docs/issues/876 , the spec authors removed the "top to bottom" part in "The t coordinate goes from 0.0 to 1.0, top to bottom."

The Vulkan tutorial in the "Loading models" chapter has the following sentence:
"The problem is that the origin of texture coordinates in Vulkan is the top-left corner, whereas the OBJ format assumes the bottom-left corner."

There is now a mismatch between the spec and the tutorial. It would be great to have your feedback on this Vulkan-Docs issue to see if the spec change makes sense or not.

**Comment by Overv** [comment]
The tutorial is not so much inconsistent with the spec, but rather a bit inexact in its wording. What the tutorial text means to say is

    The texture image has its top-left corner at (0, 0), but the texture coordinates of the model assume that the image is flipped with its top-left corner at (0, height).

The current wording treats the fact that Vulkan's linear image layout starts with the pixel at (0, 0) and Vulkan preferring a top to bottom orientation as synonymous which is somewhat misleading.

I will modify it asap to be more clear, thank you for bringing this up.
