### ISSUE TITLE
Potential out-of-bounds access

### ISSUE THREAD

**Issue by cjay** [Overv/VulkanTutorial#129]
In [part 22](https://vulkan-tutorial.com/code/22_descriptor_sets.cpp) a bunch of vectors are created with size `swapChainImages.size()`, for example descriptorSets. When recreating the swap chain, there is no check if the length of those vectors matches the length of the new swap chain. If the new swap chain is longer than the old one (no idea if that can actually happen), out-of-bounds accesses happen, for example in `createCommandBuffers` there is an access to `&descriptorSets[i]`, where the effective iteration limit for `i` is the new `swapChainImages.size()`.

**Comment by Overv** [comment]
Fixed in f89781ae89cad766e574cf4c40058ee2ecb8a23f
