### ISSUE TITLE
Makefile tutorial link broken

### ISSUE THREAD

**Issue by serid** [Overv/VulkanTutorial#131]
In "https://vulkan-tutorial.com/Development_environment#page_Setting_up_a_makefile_project" section the link "http://mrbook.org/blog/tutorials/make/" after code sample forwards to a site with some error:

![Site_screenshot](https://user-images.githubusercontent.com/30107608/57192304-8ebac500-6f37-11e9-8248-c8ed919dda6d.png)

I tried to open that link from mobile device, from another network and googled this tutorial up and got the very same error, so the problem has to be in site itself.

Probably we have to link another tutorial. E. g. this one: http://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/

**Comment by Overv** [comment]
Thanks for spotting that! I've decided to replace it with someone that is a bit more extensive and also community maintained:

https://makefiletutorial.com/
