### ISSUE TITLE
Crash in vkCreateInstance on AMD Radeon R9 200 / HD 7900 Series

### ISSUE THREAD

**Issue by Vinssou** [Overv/VulkanTutorial#133]
CallStack : 

 	amdvlk64.dll!00007ff9346dad11()	Unknown
 	amdvlk64.dll!00007ff9346daf51()	Unknown
 	vulkan-1.dll!00007ff93bce801d()	Unknown
 	vulkan-1.dll!00007ff93bcdaddc()	Unknown
 	vulkan-1.dll!00007ff93bcee31d()	Unknown
>	vkcubepp.exe!vk::DispatchLoaderStatic::vkCreateInstance(const VkInstanceCreateInfo * pCreateInfo, const VkAllocationCallbacks * pAllocator, VkInstance_T * * pInstance) Line 612	C++
 	vkcubepp.exe!vk::createInstance<vk::DispatchLoaderStatic>(const vk::InstanceCreateInfo * pCreateInfo, const vk::AllocationCallbacks * pAllocator, vk::Instance * pInstance, const vk::DispatchLoaderStatic & d) Line 48079	C++
 	vkcubepp.exe!Demo::init_vk() Line 1173	C++
 	vkcubepp.exe!Demo::init(int argc, char * * argv) Line 953	C++
 	vkcubepp.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * pCmdLine, int nCmdShow) Line 2927	C++

**Comment by Overv** [comment]
This sounds like a driver issue.

**Comment by Vinssou** [comment]
> This sounds like a driver issue.
Yes it was, I updated my driver and now it is all fine. Thanks !
