### ISSUE TITLE
Drop the VK_FORMAT_UNDEFINED case

### ISSUE THREAD

**Issue by lewa-j** [Overv/VulkanTutorial#135]
The Vulkan API Specification v1.1.111 changed the behaviour of GetPhysicalDeviceSurfaceFormats. Now it must not contain VK_FORMAT_UNDEFINED
https://github.com/KhronosGroup/Vulkan-Docs/commit/ad46c7dc688fe973ac7299b651403be5f562db8e

**Comment by Overv** [comment]
Thanks, I will update the swap chain chapter as soon as possible to no longer mention this.

**Comment by lewa-j** [comment]
Thanks for the quick response. And for your work.
