### ISSUE TITLE
Simple example of GLFW and Vulkan on Linux?

### ISSUE THREAD

**Issue by kershnerd** [Overv/VulkanTutorial#141]
This has been one of the most frustrating experiences in my life.  I am looking for a simple example of using Vulkan with glfw3.3.  I am an experienced C++ developer and experienced OpenGL programmer, but the problems I am running into have to do with just setting up a project with cLion and CMakeLists.txt.

I am able to render a window having to do with the Base Code: https://vulkan-tutorial.com/Drawing_a_triangle/Setup/Base_code

But when trying to do the next tutorial (validation layers), I always get this error:
```validation layers requested, but not available!```

**Comment by lewa-j** [comment]
Have you installed VulkanSDK with Validation Layers?

**Comment by kershnerd** [comment]
I downloaded and built the Vulkan SDK examples and was able to see the LunarG spinning cube.

Are the Validate Layers a separate build?  How do I know if they are installed?

**Comment by Overv** [comment]
Have a look at the instructions for Linux listed here: https://vulkan.lunarg.com/doc/sdk/latest/linux/getting_started.html

**Comment by kershnerd** [comment]
I guess I don't fully understand.  For some reason, I have to run:
```./vkconfig```
... to launch the vulkan configuration tool in order to use validation layers?

**Comment by Overv** [comment]
No, that's only for when applications don't enable the layers themselves.

**Comment by kershnerd** [comment]
OK... thanks!
