### ISSUE TITLE
Viewport were not provided via calls to vkCmdSetViewport

### ISSUE THREAD

**Issue by ChetanGandhi** [Overv/VulkanTutorial#144]
Hi,

I am getting this error
`Dynamic viewport(s) 0 are used by pipeline state object, but were not provided via calls to vkCmdSetViewport`

I am not sure why the validation layer started reporting this, but might be due to the new driver and Vulkan SDK.

Can you please provide more details on this API and where and how to use it.

My system configuration:
Graphics card: Nvidia GeForce 930M
Driver version: 431.60
CPU: Intel i5-6200U
Vulkan SDK: 1.1.114.0

Thanks a lot for your wonderful tutorial :)

**Comment by Overv** [comment]
Did you set `pDynamicState` to something other than `nullptr`? Because if you did and you set the viewport to be dynamic, then you must have a call to [`vkCmdSetViewport`](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkCmdSetViewport.html).

**Comment by ChetanGandhi** [comment]
Yes, you are correct. I am setting following values
`
VkDynamicState dynamicStates[] = {
    VK_DYNAMIC_STATE_VIEWPORT,
    VK_DYNAMIC_STATE_LINE_WIDTH
};
`

This code is from 3rd chapter but we are not using `vkCmdSetViewport` anywhere.
Are we missing the call to this API ?

**Comment by Overv** [comment]
No, you're just not supposed to use dynamic states in this tutorial.

**Comment by ChetanGandhi** [comment]
Ok. Thanks for clarifying this. I will remove the related code :)
