### ISSUE TITLE
Code inclusion in MarkDown to lessen traduction work ?

### ISSUE THREAD

**Issue by MacGamerFR** [Overv/VulkanTutorial#149]
Some of the update of the tutorial are only code and aside from cpp files that are shared between translations, we have to update every code portion in every translation.
So if there was a way to share these code portions between translation, that could lessen the updating process.

**Comment by Overv** [comment]
The content framework used for the tutorial doesn't really provide an option for this unfortunately.

**Comment by MacGamerFR** [comment]
OK, I'll have to look at your last commits since last merge for the French translation to update it in the next days or so.
