### ISSUE TITLE
Full system freeze

### ISSUE THREAD

**Issue by paulhilbert** [Overv/VulkanTutorial#15]
The swap_chain_creation.cpp as well as my own implementation following your tutorial up to this point reliably freezes my machine if I interact in any way with the window (moving, resizing, closing etc.). Additionally I get a "validation layer: vkDeviceWaitIdle: returned VK_ERROR_DEVICE_LOST, indicating that the logical device has been lost" error when terminating the application.

Note that SashaWillems basic triangle example works fine.

**Comment by Overv** [comment]
Which platform and hardware are you using?

**Comment by paulhilbert** [comment]
Linux (Arch Linux) 4.6.4, ph-device is nvidia gtx 780, driver 367.35.
I thought it was related to my window manager instantly resizing the window after startup since it is a tiling wm (i3), but that wasn't the case. If I manage to find some time for it this weekend I will look into the differences to the aforementioned tutorial by SashaWillems.

**Comment by kubasz** [comment]
I've had exactly the same problem (Arch Linux linux-ck 4.6.6-1, NV GTX 960 2GB 367.35) and managed to resolve it by adding fences and waiting for the graphics command buffer to execute before scheduling presentation (just like in Sasha Willem's example code [triangle.cpp line 353](https://github.com/SaschaWillems/Vulkan/blob/fd2859b81e54bb555b87ee3c5b59b4a327d94ee0/triangle/triangle.cpp#L353))

**Comment by Overv** [comment]
@kubasz It's odd that something like that is required, because `vkQueuePresentKHR` already waits on the semaphore that is signaled when the command buffer finishes execution.

**Comment by leestripp** [comment]
Hi guys, I've just got everything up to the basic triangle working under Antergos (Arch) and its all working fine.

Moving the window around is a little choppy, but that might be due to the code throwing everything at the GPU with no let up? Window close responds correctly etc.

**Comment by Overv** [comment]
@leestripp Is that without any modifications to synchronisation?

**Comment by leestripp** [comment]
Yes, no modifications.

**Comment by leestripp** [comment]
Added a sleep_for in the mainLoop. Now the window moves nice and smooth. Hope that helps.

```code
void lsVulkan::mainLoop()
{
	cout << "lsVulkan::mainLoop() called" << endl;
	while( !glfwWindowShouldClose(window) )
	{
		glfwPollEvents();
		// TODO: Add ESC support
		drawFrame();
		this_thread::sleep_for( chrono::milliseconds(1) );
	}
	vkDeviceWaitIdle( device );
}
```

**Comment by AkBKukU** [comment]
I have finished the the "Rendering and presentation" section of the tutorial and have also encountered the `validation layer: vkDeviceWaitIdle: returned VK_ERROR_DEVICE_LOST, indicating that the logical device has been lost` message. However I have tried this on two different Ubuntu systems and only one of them give the error.

No error System:
Ubuntu 15.10
Nvidia GTX 680
Driver 367.35

Has Error System:
Ubuntu 16.04
Nvidia GTX 860M
Driver 370.23

On the system with the error I rolled back to the 367.35 driver and then the error went away. So it may be a driver problem.

Looking at the supported features on gpu info for the [680](http://vulkan.gpuinfo.org/displayreport.php?id=533) vs. [960](http://vulkan.gpuinfo.org/displayreport.php?id=563), [780](http://vulkan.gpuinfo.org/displayreport.php?id=559), & [860M](http://vulkan.gpuinfo.org/displayreport.php?id=637) doesn't give any correlation between features and problems.

I put my implementation of the code up here: https://github.com/AkBKukU/VKTriangle

**Comment by rlofc** [comment]
I've just experienced the same full system freeze on window resize/move/etc with nvidia 370.28-1 under Arch.
Adding fences as @kubasz suggested resolved this for me.

**Comment by Overv** [comment]
@rlofc Can you try the following code? https://gist.github.com/Overv/2d2c1e0fe0ff270c56f7773aa5cd93f0 It relies on the same shaders as the code for the end of "Rendering and presentation"

**Comment by rlofc** [comment]
Same issue. 
Interestingly I'm also using a tiling wm (dwm). Intuitively I would say this is related.

**Comment by Overv** [comment]
Can you check if the latest code still has this issue? I've changed the way synchronization works in `drawFrame`.
