### ISSUE TITLE
Validation layer is not working

### ISSUE THREAD

**Issue by LJXLJXLJX** [Overv/VulkanTutorial#151]
I just copy and paste [02_validation_layers.cpp](https://github.com/Overv/VulkanTutorial/blob/master/code/02_validation_layers.cpp) to my project and run it, bug I didn't get any output in the console.  
My vulkan sdk version is 1.1.121.2.
Anyone can help me?

**Comment by Overv** [comment]
Please verify your Vulkan SDK installation as described [here](https://vulkan.lunarg.com/doc/sdk/1.1.121.2/windows/getting_started.html).

**Comment by LJXLJXLJX** [comment]
@Overv 
Hello, here is the output of VIA, it seems nothing wrong with installation.

> VIA_INFO:    SDK Found! - Will attempt to run tests
VIA_INFO:       Attempting to run vkcube.exe in D:\VulkanSDK\1.1.121.2\Bin
VIA_INFO:           Command-line: vkcube.exe --c 100 --suppress_popups
VIA_INFO:           Command-line: vkcube.exe --c 100 --suppress_popups --validate
SUCCESS: Vulkan analysis completed properly using Vulkan 1.1

**Comment by Overv** [comment]
Right, I just reread your message and I get now what you're doing. With the code at the end of that chapter there's not supposed to be any output since there are no mistakes for the validation layers to find.
