### ISSUE TITLE
Not seeing debug messenger output as described in the tutorial

### ISSUE THREAD

**Issue by Zingam** [Overv/VulkanTutorial#158]
I have the latest LG SDK .130 and NVIDIA/Intel driver. I use the Khronos validation layer. Everything seems fine. I checked the FAQ and VIA - I see no issues.
Yet mycode does not call the callback as described in the tutorial (I followed the "bug" instruction). I also checked the comments and some old reddit posts.

Finally I used the extension's messenger function to send a test data and that worked and I was able to see my message from the callback.

Yet I see no other validation messages as described in the tutorial thus I am not sure if my code works as expected.
Could the info be outdated with the latest SDKs. Is there anything else that I could check to see if everything is setup correctly?

**Comment by Zingam** [comment]
The reason is: the Vulkan Tutorial is outdated. Current Vulkan layers do not "print out" informational messages any longer.

**Comment by Overv** [comment]
Fixed in 2baf47799d67d6d6b43145cbd93a8d969dd2895a, thanks!
