### ISSUE TITLE
The sidebar doesn’t work

### ISSUE THREAD

**Issue by janekb04** [Overv/VulkanTutorial#159]
Clicking the sidebar button doesn’t do anything.

**Comment by Overv** [comment]
This has been fixed.

* https://github.com/Overv/daux.io/commit/241f2382b26bde7937badd27445b6c032ca72c49
* https://github.com/Overv/daux.io/commit/eecab170dd4ac04d41e0e3bc883cc8451e2bf89b

**Comment by janekb04** [comment]
Great, thanks!
