### ISSUE TITLE
Using vec3(0.0, 0.0, 1.0) for "up" in glm::lookAt instead of vec3(0.0, 1.0, 0.0)??

### ISSUE THREAD

**Issue by peterdelevoryas** [Overv/VulkanTutorial#161]
Hey, am I crazy, or is the up vector typo'd??? I noticed the view was not changing how I expected when I moved the camera along the x-axis, I assume this is the cause? Or is there something else that's making up for this?

**Comment by Overv** [comment]
Nah, this is correct. I've made the (fairly arbitrary) choice to use the Z axis for up/down in the tutorial.
