### ISSUE TITLE
Linear format when using sRGB

### ISSUE THREAD

**Issue by oierlauzi** [Overv/VulkanTutorial#163]
[When creating the swap-chain](https://github.com/Overv/VulkanTutorial/blob/master/en/03_Drawing_a_triangle/01_Presentation/01_Swap_chain.md), a `VK_FORMAT_B8G8R8A8_UNORM` format (linear) is used besides an sRGB nonlinear colorspace. As [stated in the documentation](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkColorSpaceKHR.html) nonlinear color-spaces must have the appropriate EOTF applied before its presentation. As in this case, this transfer function is not applied, there is a slight color incorrection (interpreting linear RGB data as non-linear RGB data). Therefore, I think its better to use a VK_FORMAT_B8G8R8A8_SRGB format, so that the [transfer function is applied automatically by Vulkan](https://www.gamedev.net/forums/topic/683452-when-is-srgb-conversion-being-done-in-vulkan/)

**Comment by Overv** [comment]
Are you sure about this? If I use the SRGB format then the texture looks wrong (different from how it looks in image editors). Is that because the texture loading also needs to be changed?

**Comment by oierlauzi** [comment]
Yes, you're right. If the texture is encoded as SRGB and then interpreted as linear RGB, both errors cancel out, so there isn't any problem. In most cases this will be OK, and it will be more efficient, as the TMU does not have to do the RGB<->SRGB conversion. However if there is any blending at the scene, [color mixing will be done incorrectly](https://www.youtube.com/watch?v=LKnqECcg6Gw)

**Comment by Overv** [comment]
Alright, I'll correct this in the tutorial as soon as possible.
