### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by Naitsirc98** [Overv/VulkanTutorial#165]
Hi!

I've created a Java version of your tutorial: [Vulkan-Tutorial-Java](https://github.com/Naitsirc98/Vulkan-Tutorial-Java). Since #37 seems to be abandoned, I'm creating another issue for it. 

I'd like you to take a look at it, and if you want, add a link to it in the main tutorial, just like you did with the [Rust version](https://github.com/bwasty/vulkan-tutorial-rs).

**Comment by Overv** [comment]
Cool! I'll look at it later this week.

**Comment by Overv** [comment]
Nice work! I must say that the Java code is surprisingly similar to the C++ code, which should make it very easy for people to follow along. To make it a bit more convenient I recommend adding chapter diffs just like the Rust version has done. That way it's easy to locate the code that's mentioned in the tutorial chapters.

**Comment by Naitsirc98** [comment]
Thanks for your reply! I'm glad you like it! 😄
LWJGL3 allows Java developers to easily imitate C code, which is fantastic for graphics programming.
And yes, adding chapter diffs would be great. I'll be working on them this week.

**Comment by Naitsirc98** [comment]
Hi!
I've added the chapter diffs, and I've improved the README. Now it has a table of contents matching the tutorial's webpage, and links to the original code, the Java version, and its diff for each chapter.

**Comment by Overv** [comment]
Awesome, I've added a link to the sidebar!

**Comment by Naitsirc98** [comment]
Great! I'm glad to collaborate in your fantastic tutorial! 😄
