### ISSUE TITLE
 Consider removing *_READ flag in VkSubpassDependency's srcAccess for acquire and present.

### ISSUE THREAD

**Issue by JesseRMeyer** [Overv/VulkanTutorial#168]
https://github.com/Overv/VulkanTutorial/blob/56389adfef6d51493df7a50475fcf01c36f75c4d/code/15_hello_triangle.cpp#L412

Based on my readings from this conversation : https://github.com/KhronosGroup/Vulkan-Docs/issues/131#issuecomment-248673629, and that the *_READ flag is not in the official Synchronization Example for Swapchain Image Acquire and Present usage cases: https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples#swapchain-image-acquire-and-present, I believe it can be removed.

**Comment by Overv** [comment]
Thanks for spotting this. Now that I look at it again it made no sense that said flag was specified there.
