### ISSUE TITLE
Physical_devices_and_queue_families code question

### ISSUE THREAD

**Issue by mj-saunders** [Overv/VulkanTutorial#173]
Not so much an issue as a question.

Regarding this page: https://vulkan-tutorial.com/en/Drawing_a_triangle/Setup/Physical_devices_and_queue_families

Regarding the very last code block.

indices.isComplete() is used to check whether to break out of the for loop.
Is this not an un-necessary check?
Is it not simpler to simply break once `indices.graphicsFamily = i` is run?

Maybe I'm missing something...

**Comment by Overv** [comment]
In that chapter yes, but the check will be more extensive in the later chapters.
