### ISSUE TITLE
Command buffers section on VkCommandPoolCreateInfo flag set to 0.

### ISSUE THREAD

**Issue by Bambofy** [Overv/VulkanTutorial#182]
Hi,
https://vulkan-tutorial.com/Drawing_a_triangle/Drawing/Command_buffers here you say that the flags field is optional however Vulkan technically has no optional fields.

See https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VkCommandPoolCreateInfo

> Valid Usage (implicit)
> flags **must** be a valid combination of VkCommandPoolCreateFlagBits values

From the "Vulkan Programming Guide" book, it suggests to set both VK_COMMAND_POOL_CREATE_TRANSIENT_BIT and  VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT

**Comment by MacGamerFR** [comment]
You can zero the flag parameter :
`VkCommandPoolCreateFlags is a bitmask type for setting a mask of zero or more VkCommandPoolCreateFlagBits.`

**Comment by Bambofy** [comment]
> You can zero the flag parameter :
> `VkCommandPoolCreateFlags is a bitmask type for setting a mask of zero or more VkCommandPoolCreateFlagBits.`

Yeah it says you can set it to zero but the book says you shouldn't, you should set both transient and reset command bits instead

**Comment by Overv** [comment]
`VK_COMMAND_POOL_CREATE_TRANSIENT_BIT` is not applicable since the command buffers in the tutorial are not short-lived and neither is `VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT` because the command buffers are never reset.

**Comment by Bambofy** [comment]
> `VK_COMMAND_POOL_CREATE_TRANSIENT_BIT` is not applicable since the command buffers in the tutorial are not short-lived and neither is `VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT` because the command buffers are never reset.

ah i think i misundertood the api, it says any valid combination of bits, 0 is a valid combination :)
