### ISSUE TITLE
MVP Transformation resource not available

### ISSUE THREAD

**Issue by Tooniis** [Overv/VulkanTutorial#188]
The resource for MVP transformations referred to [here](https://vulkan-tutorial.com/Uniform_buffers/Descriptor_layout_and_buffer) is not available. I don't know if it is down only temporarily, but I'd suggest just replacing it with [this](https://www.opengl-tutorial.org/beginners-tutorials/tutorial-3-matrices/).

**Comment by Overv** [comment]
Ah, the arcsynthesis tutorial keeps disappearing from the internet. I've changed it to the link you suggested.
