### ISSUE TITLE
setting up Vulkan on Linux needs updates

### ISSUE THREAD

**Issue by ericoporto** [Overv/VulkanTutorial#189]
Ubuntu 20.04 has been released. GLFW can now be safely installed from apt to get a very recent version.

```
sudo apt install libglfw3-dev 
``` 

Maybe there is an easier way too to get the Lunar package, [but so far they haven't been updated for Ubuntu 20.04 yet](https://packages.lunarg.com/).

The sdk also doesn't have an `./build_examples.sh` script so I am not sure what to do after downloading.

**Comment by abnercoimbre** [comment]
An official `build_examples.sh` could exist, but we'd have to iron out some important details:

* Do we assume Linux users have glslc installed and on the PATH? If GLFW or GLM are missing, do we teach them how to download these or attempt to install things locally? If the script dies an ugly death, lots of github issues will be created.

* What's the preferred default compiler? $CC? gcc? clang?

*  The `code/` folder doesn't have a local `shaders/` where most example programs expect the compiled shaders to live. 

For my Ubuntu 20.04 setup I have a poorman's `build.sh` inside `code/`. I assume the latest clang is installed:

```
#!/usr/bin/env bash

SRC=$1 # e.g. 15_hello_triangle.cpp
SHADER_VERT=$2 # e.g. 09_shader_base.vert
SHADER_FRAG=$3 # e.g. 09_shader_base.frag

# Create shaders folder if needed
if [ ! -d shaders ]; then
  mkdir shaders
fi

# Exit if GLM isn't installed locally (remove check if it's available system-wide)
if [ ! -d glm ]; then
  echo 'glm library not in this folder' ; exit 1;
fi

# Compile shaders; we assume glslc is installed and on the PATH
pushd shaders
  glslc ../$SHADER_VERT -o vert.spv
  glslc ../$SHADER_FRAG -o frag.spv
popd

clang++ -std=c++17 -I. $SRC -lglfw3 -lvulkan -ldl -lm -lpthread
```

My script takes three arguments (order matters in this simple script):

1. Example program

2. Vertex shader

3. Fragment shader

This lets me compile the Hello Triangle program like so:

`./build.sh 15_hello_triangle.cpp 09_shader_base.vert 09_shader_base.frag`

or the Index buffer program with the colored quad:

`./build.sh 20_index_buffer.cpp 17_shader_vertexbuffer.vert 17_shader_vertexbuffer.frag`

**Comment by ericoporto** [comment]
So, `glslc` is provided with the LunarG package and alternatively can also be downloaded in unsupported binaries from the shaderc Google project page - without matching a release version.

There are some vulkan packages in Ubuntu but I can't figure out if any of them are relevant 
, except maybe `vulkan-validationlayers-dev` ?

I tried to document me trying to follow the tutorial here: https://github.com/ericoporto/vulkanLearning

I also have some messages on stderr reported here : https://gist.github.com/ericoporto/a3589a179dfc80268247347ad06e55ca

**Comment by abnercoimbre** [comment]
I'll have to go back and see what I did step-by-step to get the tutorials working on Ubuntu 20.04. I'll start that process tonight.

Based on your feedback I think we should go ahead and try to write that `build_examples.sh`, or at the very least document how to get up-and-running without the Lunar package.

**Comment by abnercoimbre** [comment]
Ookay dug through my bash history and found the steps I took:

- `sudo apt install libglfw3-dev`: Installs latest [GLFW](https://www.glfw.org/) library, as you've noted.

- `sudo apt install libglm-dev`: Installs latest [GLM](https://glm.g-truc.net/0.9.9/index.html) library.

- `sudo apt install vulkan-tools`: Useful utilities, most importantly `vulkaninfo` and `vkcube`. I ran these to confirm my machine is Vulkan-capable.

- `sudo apt install libvulkan-dev`: Installs [Vulkan loader](https://github.com/KhronosGroup/Vulkan-Loader)

- `sudo apt install vulkan-validationlayers-dev`: Installs the [validation layers](https://github.com/KhronosGroup/Vulkan-ValidationLayers).

Finally I wanted to install `spirv-tools` but found it too confusing. I simply did what you did: downloaded Google's [unofficial binaries](https://github.com/google/shaderc/blob/main/downloads.md), and moved `glslc` to my `/usr/local/bin` folder.

Let me know if this "works on your machine" :wink:. Note that after finding these packages, I skipped the LunarG SDK entirely. Instead I use my own build script or Makefile.

**Comment by ericoporto** [comment]
@abnercoimbre HEEEY IT WORKS!

![Screenshot from 2020-06-23 09-59-32](https://user-images.githubusercontent.com/2244442/85406479-4514ab80-b538-11ea-9eaf-a56501dd4288.png)

In my Linux it's `-lglfw` and not `-lglfw3` for some reason.

```
g++ -std=c++17 15_hello_triangle.cpp -lglfw -lvulkan -ldl -lm -lpthread
```

**Comment by abnercoimbre** [comment]
Awesome! You should be able to compile any program in the tutorial now. For those reading this, you can replace `g++` with `clang++` and the command still works:

`clang++ -std=c++17 15_hello_triangle.cpp -lglfw -lvulkan -ldl -lm -lpthread`

> In my Linux it's -lglfw and not -lglfw3 for some reason.

That was a typo on my end; I've fixed the instructions along with other edits to make the instructions more professional.

> I think I will move to other things now and return to Vulkan later. Thank you for the help.

No problem. To close this issue, I could make a PR to update the Linux [Development environment](https://vulkan-tutorial.com/Development_environment#page_Linux) section saying the LunarG SDK won't support Ubuntu 20.04 for a while. We either link to this issue for a possible workaround, or update the chapter text with instructions? We should wait and see what @Overv has to say :)

**Comment by Overv** [comment]
I'll get back to this on Saturday :)

**Comment by Overv** [comment]
For GLFW it makes sense at this point to just recommend installing it from a standard package, but with the Vulkan SDK and its validation layers I'm curious how up-to-date the `vulkan-validationlayers-dev` package will be at any point in time. Do you know if it's updated soon after a new version is released?

**Comment by abnercoimbre** [comment]
Sorry I've taken a while to respond -- life suddenly got hectic after your reply. Things are slowing down so I'll get back to this thread this week :)

**Comment by abnercoimbre** [comment]
@Overv I'm still alive! This year is a real peach.

> For GLFW it makes sense at this point to just recommend installing it from a standard package

Yeah, agreed.

> I'm curious how up-to-date the `vulkan-validationlayers-dev` package will be at any point in time. Do you know if it's updated soon after a new version is released?

They're maintained through [MOTU](https://wiki.ubuntu.com/MOTU) which I think is already a good sign. Scanning the [changelogs](https://changelogs.ubuntu.com/changelogs/pool/universe/v/vulkan-validationlayers/) shows they're pretty on top of the validation layers, updating them as recently as last month. That pace is faster than LunarG SDK, who have yet to upgrade their packages for Ubuntu 20.04.

**Comment by Overv** [comment]
@abnercoimbre Would you be willing to create a PR with updates for the Linux instructions based on your findings?
