### ISSUE TITLE
15_hello_triangle.cpp does not draw anything on the screen on MacOS

### ISSUE THREAD

**Issue by nelson-xia** [Overv/VulkanTutorial#191]
My Environment:
OS: MacOS 10.14.6
SDK: vulkansdk-macos-1.2.141.2
vert.spv from 09_shader_base.vert
frag.spv from 09_shader_base.frag 

when I run the same codes on Linux,  the colorful triangle is drawn correctly.

**Comment by Overv** [comment]
I cannot reproduce this problem on either Arch Linux or Windows 10 (NVIDIA GTX 1070 with latest drivers) and it seems like a strange error given that the shader doesn't have any inputs. Make sure that you've really compiled the right source file to the right output files.
