### ISSUE TITLE
Tutorial example make file has an error

### ISSUE THREAD

**Issue by Taracandra** [Overv/VulkanTutorial#196]
LDFLAGS = -L$(VULKAN_SDK_PATH)/lib 'pkg-config --static --libs glfw3' -lvulkan
should be : 
LDFLAGS = -L$(VULKAN_SDK_PATH)/lib \`pkg-config --static --libs glfw3\` -lvulkan
so ' is not ` and unfortunately this throws an error. 
Using Ubuntu20.4

**Comment by Overv** [comment]
Where did you see the version with wrong quotes?

**Comment by lewa-j** [comment]
here https://github.com/Overv/VulkanTutorial/blob/master/en/02_Development_environment.md#L374

**Comment by Taracandra** [comment]
I must have typed that part and thought, like usual, that it was a
copy-paste action.

This make file example looks ok, so the error was from me, and great
apologies for the inconvenience.

----------------------------------------------------------------------------------------------------
VULKAN_SDK_PATH = /home/user/VulkanSDK/x.x.x.x/x86_64

CFLAGS = -std=c++17 -I$(VULKAN_SDK_PATH)/include
LDFLAGS = -L$(VULKAN_SDK_PATH)/lib `pkg-config --static --libs glfw3` -lvulkan

VulkanTest: main.cpp
    g++ $(CFLAGS) -o VulkanTest main.cpp $(LDFLAGS)

.PHONY: test clean

test: VulkanTest
    LD_LIBRARY_PATH=$(VULKAN_SDK_PATH)/lib
VK_LAYER_PATH=$(VULKAN_SDK_PATH)/etc/vulkan/explicit_layer.d
./VulkanTest

clean:
    rm -f VulkanTest
