### ISSUE TITLE
validation layer: SPIR-V module not valid: Invalid SPIR-V magic number.

### ISSUE THREAD

**Issue by leestripp** [Overv/VulkanTutorial#20]
Your hello triangle builds fine, the window opens but doesn't get filled with black and  I get this error.

        validation layer: SPIR-V module not valid: Invalid SPIR-V magic number.

I've tried google, but found nothing. I'll keep looking.

# My setup
Antergos Linux 4.7.0-1-ARCH 
glinfo  :
GL_VERSION: 4.5.0 NVIDIA 367.35
GL_RENDERER: GeForce GTX 970/PCIe/SSE2
GL_VENDOR: NVIDIA Corporation

## Screenshot
![screenshot from 2016-08-13 12-46-36](https://cloud.githubusercontent.com/assets/20528673/17641195/1c732792-6159-11e6-85e3-04bc9a2f1dda.png)

**Comment by Overv** [comment]
Please upload the two spv files you compiled.

**Comment by leestripp** [comment]
I installed glslang again and its fixed. Sorry about that.

![screenshot from 2016-08-13 20-30-42](https://cloud.githubusercontent.com/assets/20528673/17642744/a2894f14-6195-11e6-854b-848722c7cdc1.png)
