### ISSUE TITLE
Depth buffering: Note regarding transparent objects

### ISSUE THREAD

**Issue by maltekliemann** [Overv/VulkanTutorial#203]
In chapter _Depth buffering_, section _Depth and stencil state_ (emphasis is mine):

> The `depthWriteEnable` field specifies if the new depth of fragments that pass the depth test should actually be written to the depth buffer. This is useful for drawing transparent objects. They should be compared to the previously rendered opaque objects, but not cause further away *transparent* objects to not be drawn.

~~The bold *transparent* is not required, right?~~

~~Also, maybe _transparent_ should be replaced by _fully transparent_ to emphasize that the alpha channel must be strictly zero. A partially transparent object (a tinted window, for example) should most likely not be ignored in depth testing.~~

I'm really confused about this paragraph. I don't understand what rendering technique you're describing. If I had to guess, I'd say that you want to render opaque objects first, then render (partially) transparent objects over them in arbitrary order. Not writing to the depth buffer prevents near transparent objects from occluding far transparent objects. But depending on the order in which the transparent objects are rendered, I think you need different blending operations, so you have to keep track of the order one way or another.

**Comment by Overv** [comment]
Yeah, looking at it again now, it doesn't make any sense since it implies that you'd render near transparent objects before farther ones.
