### ISSUE TITLE
daux.patch only located in develop branch

### ISSUE THREAD

**Issue by maltekliemann** [Overv/VulkanTutorial#209]
~~If this is intentional, then I think the `README.md` should mention in section **Clone, patch, and rebuild daux** that the file must be taken from another branch.~~

Okay, I figured out that building the tutorial must happen in the `develop` branch. Maybe this could be mentioned in the `README.md`?

**Comment by Overv** [comment]
It should be built from [this Dockerfile](https://github.com/Overv/daux.io/blob/vulkan-tutorial/Dockerfile), which uses the `master` branch of this repo.

**Comment by maltekliemann** [comment]
Oh, my bad... :( Thanks!
