### ISSUE TITLE
Updating a link to tinyobjloader

### ISSUE THREAD

**Issue by syoyo** [Overv/VulkanTutorial#21]
First of all, thank you for great vulkan tutorial!

Secondary, `develop` branch of TinyObjLoader is now merged into `master`, thus please update the information of TinyObjLoader in Loading models section(https://vulkan-tutorial.com/Loading_models)  to point to the `master` branch.

**Comment by Overv** [comment]
I've updated the tutorial. Thanks for the nice library :)

**Comment by syoyo** [comment]
Thank you!
