### ISSUE TITLE
Discrepancy between full code and snippet

### ISSUE THREAD

**Issue by David-DiGioia** [Overv/VulkanTutorial#215]
In the section ["Texture mapping > Combined image sampler"](https://vulkan-tutorial.com/Texture_mapping/Combined_image_sampler) the code snippet where we add texture coordinates is
```
const std::vector<Vertex> vertices = {
    {{-0.5f, -0.5f}, {1.0f, 0.0f, 0.0f}, {0.0f, 0.0f}},
    {{0.5f, -0.5f}, {0.0f, 1.0f, 0.0f}, {1.0f, 0.0f}},
    {{0.5f, 0.5f}, {0.0f, 0.0f, 1.0f}, {1.0f, 1.0f}},
    {{-0.5f, 0.5f}, {1.0f, 1.0f, 1.0f}, {0.0f, 1.0f}}
};
```
But in the [full code for this section](https://vulkan-tutorial.com/code/25_texture_mapping.cpp) it is
```
const std::vector<Vertex> vertices = {
    {{-0.5f, -0.5f}, {1.0f, 0.0f, 0.0f}, {1.0f, 0.0f}},
    {{0.5f, -0.5f}, {0.0f, 1.0f, 0.0f}, {0.0f, 0.0f}},
    {{0.5f, 0.5f}, {0.0f, 0.0f, 1.0f}, {0.0f, 1.0f}},
    {{-0.5f, 0.5f}, {1.0f, 1.0f, 1.0f}, {1.0f, 1.0f}}
};
```
Notice the difference in texture coordinates. One is the mirror image of the other. The images in the tutorial disagree with the first code snippet and agree with the second, which can cause some confusion when you're following along.

**Comment by Overv** [comment]
Thanks for spotting that, I've fixed it!
