### ISSUE TITLE
maxSamplerAnisotropy limits not verified

### ISSUE THREAD

**Issue by maltekliemann** [Overv/VulkanTutorial#216]
In *Texture mapping > Image view and sampler*, you're using a fixed `maxSamplerAnisotropy = 16.0f`. But [VUID-VkSamplerCreateInfo-anisotropyEnable-01071](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSamplerCreateInfo-anisotropyEnable-01071) of Vulkan 1.2 states:

> If `anisotropyEnable` is `VK_TRUE`, `maxAnisotropy` must be between `1.0` and VkPhysicalDeviceLimits::maxSamplerAnisotropy`, inclusive

So it should either be `maxSamplerAnisotropy = properties.limits.maxSamplerAnisotropy` (assuming `16.0f` is the maximum), or you check during physical device selection if `16.0f` is available. The former makes a lot more sense to me, but I wasn't sure which one you would prefer.

**Comment by Overv** [comment]
Ah, right, will fix that tomorrow!
