### ISSUE TITLE
Uninitialized structs cause trouble for experimenting readers

### ISSUE THREAD

**Issue by jediflamaster** [Overv/VulkanTutorial#217]
```VkDebugUtilsMessengerCreateInfoEXT debugCreateInfo;```
^ this in particular caused some trouble for me. As suggested in the tutorial I've made a function that checks whether required extensions are available. This produced trash on stack, which was then used to populate this struct. This, in turn, resulted in a segmentation fault on creating instance. Please use
```VkDebugUtilsMessengerCreateInfoEXT debugCreateInfo{};``` I'm not sure if this is a repeating pattern because I'm still not that far into the tutorial.

**Comment by Overv** [comment]
`debugCreateInfo` is initialized by `populateDebugMessengerCreateInfo` if the validation layers are enabled. It shouldn't be used otherwise.
