### ISSUE TITLE
std::optional error

### ISSUE THREAD

**Issue by lukasino1214** [Overv/VulkanTutorial#219]
Hi. I am following tutorial. My IDE throwing error `qualified name is not allowed`. On line with `std::optional<uint32_t> graphicsFamily;`. Can you help me with it?

Thanks

![image](https://user-images.githubusercontent.com/38435841/100484274-f927ed00-30fb-11eb-98df-78afa9a2f3ac.png)
![image](https://user-images.githubusercontent.com/38435841/100484291-0e048080-30fc-11eb-8d4d-815f01564f74.png)

**Comment by Krenodeno** [comment]
Hi !
You need to set your compiler to C++17 standard.

**Comment by lukasino1214** [comment]
Thanks! It was problem with extensions in VSCode it was set to gnu++14. Now it´s `Failed to open file!`. I don´t know what file failed to open.
