### ISSUE TITLE
correction en/03_Drawing_a_triangle/02_Graphics_pipeline_basics/04_Conclusion.md

### ISSUE THREAD

**Issue by hwpfeil** [Overv/VulkanTutorial#227]
"We start by referencing the array of VkPipelineShaderStageCreateInfo structs."

Should not that reference be "VkGraphicsPipelineCreateInfo" pointing to
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkGraphicsPipelineCreateInfo.html?

**Comment by Overv** [comment]
No, that instruction is referring to this line:

```c++
pipelineInfo.pStages = shaderStages;
```
