### ISSUE TITLE
Installation on Fedora linux

### ISSUE THREAD

**Issue by bkmgit** [Overv/VulkanTutorial#232]
The current linux instructions for [English](https://github.com/Overv/VulkanTutorial/blob/master/en/02_Development_environment.md) and [French](https://github.com/Overv/VulkanTutorial/blob/master/fr/02_Environnement_de_d%C3%A9veloppement.md) are for Ubuntu, a deb based distribution. It may be helpful to have instructions for Fedora linux, an RPM based distribution. Required commands are:

- sudo dnf -y install vulkan-tools vulkan-headers vulkan-loader-devel mesa-vulkan-devel vulkan-validation-layers-devel
- sudo dnf -y install glfw-devel
- sudo dnf -y install glm-devel
- sudo dnf -y install glslc

Can make a pull request with suggested modifications if it seems ok.

**Comment by Overv** [comment]
Yes, that would be nice since I have no experience with RPM distros at all.

**Comment by bkmgit** [comment]
@Overv see 
- https://github.com/bkmgit/VulkanTutorial/pull/1 
- https://github.com/bkmgit/VulkanTutorial/pull/2

**Comment by Overv** [comment]
Looks good to me!

**Comment by bkmgit** [comment]
Great, added pull request to correct tutorial repository.

**Comment by bkmgit** [comment]
addressed in https://github.com/Overv/VulkanTutorial/pull/234 and https://github.com/Overv/VulkanTutorial/pull/235
