### ISSUE TITLE
Title for the ebook

### ISSUE THREAD

**Issue by Zingam** [Overv/VulkanTutorial#236]
I suggest to put some kind of Title Image/Page in the ebooks. It actually matters on ereaders as they display it as an icon.
For these devices also the meta-data: title, author, etc. matters as can be added via calibre.

**Comment by Overv** [comment]
Could you elaborate? I don't have an ereader that supports epub myself to check, but the file explorer I use on Linux shows a title and author for both the PDF and epub files.

**Comment by Zingam** [comment]
As it is easier for me I'll give an example with `calibre`.

Currently Vulkan Tutorial appears like so in calibre:
![Screenshot 2021-05-13 191228](https://user-images.githubusercontent.com/3337419/118155044-7633ee00-b420-11eb-87f8-147a9fce3a23.png)

Some random book with cover metadata:
![Screenshot 2021-05-13 191216](https://user-images.githubusercontent.com/3337419/118155061-7a600b80-b420-11eb-9ef8-24b4a2265ed1.png)

And then I added some random image via calibre:
![Screenshot 2021-05-13 192251](https://user-images.githubusercontent.com/3337419/118155202-a4b1c900-b420-11eb-9899-564a7c647fe4.png)

Due to the lack of a cover as seen in calibre on ereaders the Vulkan Tutorial appears as a blank.


https://ebooks.stackexchange.com/questions/1186/how-do-i-add-a-cover-and-other-pictures-to-my-epub

**Comment by Zingam** [comment]
According to https://pandoc.org/MANUAL.html all that is needed is:

>--epub-cover-image=FILE
Use the specified image as the EPUB cover. It is recommended that the image be less than 1000px in width and height. Note that in a Markdown source document you can also specify cover-image in a YAML metadata block (see EPUB Metadata, below).

`pandoc -o ../epub/book.epub title.txt ch*.md --epub-cover-image=../images/cover.png`

**Comment by Overv** [comment]
Would something like this be okay as cover image? (I can't really think of anything else.)

<kbd><img src="https://user-images.githubusercontent.com/285063/118302985-32ef8300-b4e5-11eb-9e37-f6a7d8eecec7.png" width="300" /></kbd>

**Comment by Zingam** [comment]
Cool! You could always put a screenshot of the end result :)

**Comment by Zingam** [comment]
Here is a quick one from me with screenshot of the site:

:)

[Cover.zip](https://github.com/Overv/VulkanTutorial/files/6480666/Cover.zip)
![Cover](https://user-images.githubusercontent.com/3337419/118315086-b9b05a00-b4fd-11eb-9a93-77f3fd0910ee.png)

**Comment by Zingam** [comment]
One more GIMP file:
[Cover2.zip](https://github.com/Overv/VulkanTutorial/files/6480738/Cover2.zip)

**Comment by Overv** [comment]
I like your idea of including the scene in the cover image, but I'm not sure how that works in terms of licensing, so I went for something straightforward:

<kbd><img src="https://user-images.githubusercontent.com/285063/118408888-f1e3a400-b687-11eb-8278-7cdb95bbc407.png" width="400" /></kbd>

**Comment by Overv** [comment]
Fixed in c9c2762559b8730e7188fa73bff76bccf18e9e8e
