### ISSUE TITLE
Suggestion: Add development environment configuration instructions for Arch Linux?

### ISSUE THREAD

**Issue by chirsz-ever** [Overv/VulkanTutorial#238]
On Arch Linux and other pacman-based distributions, its just need one command to install Vulkan packages ~and the shader compiler~:

```sh
sudo pacman -S vulkan-devel
```

And it is also easy to install `glm` and `glfw`:

```sh
sudo pacman -S glm glfw-x11 # glfw-wayland for wayland users
```

My motivation is that some pakages' name are varied in distruibutions.

---

Fix: The package `shaderc` provides `glslc`.

**Comment by Lephar** [comment]
And `shaderc` package is required for `glslc`
