### ISSUE TITLE
Typo in Graphics Pipeline Conclusion

### ISSUE THREAD

**Issue by saveman71** [Overv/VulkanTutorial#24]
At the last paragraph:

> Now run your program and you'll see that all of the hard work has finally paid off! We are already getting quite close to seeing **the that** triangle pop up on the screen. In the next couple of chapters we'll set up the actual framebuffers from the swap chain images and prepare the drawing commands.

Would have opened a PR but I was not sure which variant you meant/prefer.

Also, I find that this paragraph is a little misleading, I thought I should have seen something on my screen,  [and this comment thought too](https://vulkan-tutorial.com/Drawing_a_triangle/Graphics_pipeline_basics/Conclusion#comment-2839332543).

You should make more clear that we're not done yet ;)

**Comment by Overv** [comment]
You're right, I've changed the wording of that paragraph.
