### ISSUE TITLE
Exception-safe programming

### ISSUE THREAD

**Issue by Tbone2401** [Overv/VulkanTutorial#25]
As I'm following the tutorial (part 3 creating the VDeleter 00_Setup/00_Base_code) and I noticed the assignment operator isn't checking for self assignment.
Is this the intention or not, or am I missing something?

**Comment by Overv** [comment]
Do you feel that it is necessary to add that?

**Comment by Tbone2401** [comment]
Actually yes, accidents happen and I'd like to catch them as soon as possible.

**Comment by Overv** [comment]
You're right. Do you think it should have more safeguards besides that one to bring it closer to the robustness of `unique_ptr`?

**Comment by Tbone2401** [comment]
Why do you think I am following this tutorial? :D
Thank you for adding it in, and thank you for listening to me. :)
