### ISSUE TITLE
lXxf86vm and lXi linker option on Ubuntu 20

### ISSUE THREAD

**Issue by sihyeon-kim** [Overv/VulkanTutorial#275]
I've been following Development environment.
In my case on Ubuntu 20.04, `-lXxf86vm` and `-lXi` linker option is not working.

```
$ make test
g++ -std=c++17 -O2 -o VulkanTest main.cpp -lglfw -lvulkan -ldl -lpthread -lX11 -lXxf86vm -lXrandr -lXi
/usr/bin/ld: cannot find -lXxf86vm
/usr/bin/ld: cannot find -lXi
collect2: error: ld returned 1 exit status
make: *** [Makefile:5: VulkanTest] Error 1
```

Without these options, I think it works like below.

```
$ make test
g++ -std=c++17 -O2 -o VulkanTest main.cpp -lglfw -lvulkan -ldl -lpthread -lX11 -lXrandr
./VulkanTest
18 extensions supported
```

Is it better to manually install libraries?

**Comment by fake-rookie** [comment]
i think you maybe need check the **Library Name** on Ubuntu.
Ubuntu always chage name of library.

**Comment by Overv** [comment]
That just means that you are missing the packages `libxxf86vm-dev libxi-dev`. I'll mention that in the tutorial.
