### ISSUE TITLE
Backside of model culled

### ISSUE THREAD

**Issue by mtvec** [Overv/VulkanTutorial#277]
After completing the "Loading model" chapter, the backside of the model seems to be mostly culled:

![image](https://user-images.githubusercontent.com/1546739/158848804-77753c5c-4cdb-4cc3-ad56-15416670cd67.png)

When I set `VkPipelineRasterizationStateCreateInfo::cullMode` to `VK_CULL_MODE_NONE` the model is rendered correctly but this is obviously not desirable.

Is this an issue with the model itself (e.g., inconsistent winding order of the triangles) or can this be fixed in the renderer?

**Comment by Overv** [comment]
I checked the model in Blender and the faces are culled there too when enabling backside culling, so I think the model is "designed" like this. Considering how it looks even with culling disabled, I think it's simply not designed to be viewed from this side.

**Comment by mtvec** [comment]
Right, I guess I was confused because it looks "better" on sketchfab and when culling is disabled.

Could it be a good idea to mention something about this in the tutorial? Especially since the model is rotating in the example code so you get to see the model from its "bad" side.
