### ISSUE TITLE
Useless dependency in Tutorial 03.03

### ISSUE THREAD

**Issue by qnope** [Overv/VulkanTutorial#28]
You are making a subpass dependency between "before the renderpass" and the subpass 0.

As you wrote your dependency, it can be understandable like "I am waiting for the presentation finish to read".
However, presentation engine is asynchronous and synchronisation for it should be done via Semaphore. Moreover semaphores make memory available and visible : 

> This semaphore signal operation defines the first half of a memory dependency, guaranteeing that all memory accesses defined by the submitted queue operations in the batch are made available, and that those queue operations have completed execution.

> A semaphore wait operation defines the second half of a memory dependency for the semaphores being waited on. This half of the memory dependency guarantees that the first half has completed execution, and also guarantees that all available memory accesses are made visible to the queue operations in the batch.

The semaphore we are talking about is the semaphore that you use inside the `vkAcquireNextImageKHR`.

> The presentation engine may not have finished reading from the image at the
time it is acquired, so the application must use semaphore and/or fence to ensure that the image layout and contents
are not modified until the presentation engine reads have completed.

So, to me you do not need to use a dependency since the layout transition is performed by the renderpass itself, and the _memory dependencies / execution dependencies_ are performed by the semaphore.

**Comment by Overv** [comment]
Yes, I understand what you're saying.

The reason that dependency is there is not for synchronisation purposes, but because I read somewhere that the initial layout transition of a render pass is only performed if you have a dependency between external and the first subpass. By default Vulkan will only perform layout transitions inbetween subpasses, however this explanation may be false.

I'll verify if this info is true or false, because the code does indeed function correctly without a dependency on my hardware.

**Comment by Overv** [comment]
You appear to be correct, since the two dependencies that are necessary for the layout transitions are implicit. I will update the tutorial as soon as possible.

**Comment by qnope** [comment]
The fact is you do not explicitly tell Vulkan to transition this image. From how I understand specs. The will be mean to mean that it will be transitioned.

Admit you are right and you do need a dependency. You want to transition the image to the layout UNDEFINED. You already know that your reads from the presentation engine are over (thanks to semaphores)! So, you do not need a dependency in this case. Am I wrong?

Let's take a look for a subpass.

The specs tell :
> layout is a VkImageLayout value specifying the layout the attachment uses during the subpass. The implementation will automatically perform layout transitions as needed between subpasses to make each subpass use the requested layouts.

The transition layout To COLOR_ATTACHMENT is automatic.

So, in my understand, you do not need a dependency

**Comment by Overv** [comment]
The section you quoted is about layout transitions between subpasses, not between VK_SUBPASS_EXTERNAL and the subpasses. However, you're still correct, because the dependencies between external and subpass, and subpass and external are implicitly added.

**Comment by Overv** [comment]
However, maybe it is better to keep it in the tutorial to make it explicit what's going on. Because otherwise I would completely remove any mention of subpass dependencies in the tutorial.

**Comment by qnope** [comment]
Yes but it is also good for the first (and only here) subpass ;).

Yeah, maybe you could let it or try to explain in a better way what subpass dependencies are and their link with PipelineBarrier.

**Comment by Overv** [comment]
Hmm, I'm still not entirely sure about this. The semaphore is used to wait in the `VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT` stage, but the implicit initial dependency will perform the transition earlier than that.

**Comment by qnope** [comment]
Hmmm, yes you are right...
So it seems we _can_ be both correct :
The first way is to use `STAGE_COLOR_ATTACHMENT` for the semaphore with a dependency that wait the read.
The second way could be to use `TOP_OF_PIPE` for semaphore, since when TOP_STAGE happened, you did not reached the `vkBeginRenderPass`, or at least, I think that.

**Comment by Overv** [comment]
Yes, I can mention the second option as alternative in the tutorial.
