### ISSUE TITLE
Output is not looking like 3d

### ISSUE THREAD

**Issue by rag3456** [Overv/VulkanTutorial#287]
Hello,

I don't have gpu in my laptop.

I tried your repository and it is running fine but the output doesn't look like 3d. It looks like 2d with some points put together. 

It displays this in the output when vert.spv and frag.spv from another source is used:

validation layer: Validation Error: [ VUID-vkCmdDrawIndexed-maintenance4-06425 ] Object 0: handle = 0x559e186d5a90, type = VK_OBJECT_TYPE_COMMAND_BUFFER; Object 1: handle = 0xdcc8fd0000000012, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; Object 2: handle = 0xd175b40000000013, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0x90b8b122 | vkCmdDrawIndexed(): Shader in VK_SHADER_STAGE_VERTEX_BIT uses push-constant statically but vkCmdPushConstants was not called yet for pipeline layout VkPipelineLayout 0xdcc8fd0000000012[]. The Vulkan spec states: If the maintenance4 feature is not enabled, then for each push constant that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a push constant value must have been set for the same pipeline bind point, with a VkPipelineLayout that is compatible for push constants, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility (https://vulkan.lunarg.com/doc/view/1.3.211.0/linux/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-maintenance4-06425)

This repository doesn't provide vert.spv and frag.spv and when the path is changed to 27_shader_depth.frag and 27_shader_depth.vert it throws error when reading the file. Maybe can you provide the proper spv files with this repo?

Thankyou.

**Comment by rag3456** [comment]
It worked with viking obj but I want to load other obj files and when I specify the path for other obj files they either show black screen or they throw segmentation fault (core dumped). 

Can anyone maybe help me with this.

**Comment by Overv** [comment]
The spv files are not provided because they are compiled files. You can compile the shaders yourself using the instructions provided [here](https://vulkan-tutorial.com/Drawing_a_triangle/Graphics_pipeline_basics/Shader_modules#page_Compiling-the-shaders).

**Comment by rag3456** [comment]
I could see the viking obj file but if I am using another obj file it doesnot show the output. It is just blank. I used 27_shader_depth.frag and vert files loading viking obj file but when I use my obj file it doesn't show any output. The window is just blank.
For example this obj file I am trying to load but the display is just blank.
[demo.zip](https://github.com/Overv/VulkanTutorial/files/8675471/demo.zip)

**Comment by rag3456** [comment]
The issue is resolved
