### ISSUE TITLE
Synchronization in Tutorial 06 : Images

### ISSUE THREAD

**Issue by qnope** [Overv/VulkanTutorial#29]
You are loading an image from the CPU.
If you want to use it in the GPU (through a command buffer), the spec says :

> For host writes to be seen by subsequent command buffer operations, a pipeline barrier from a source of VK_ACCESS_HOST_WRITE_BIT and VK_PIPELINE_STAGE_HOST_BIT to a destination of the relevant device pipeline stages and access types must be performed. Note that such a barrier is performed implicitly upon each command buffer submission, so an explicit barrier is only rarely needed

As I understand, it performs a kind of a global memory barrier with :

    srcStage = VK_PIPELINE_STAGE_HOST_BIT;
    srcAccess = VK_ACCESS_HOST_WRITE_BIT;
    dstStage = VK_PIPELINE_STAGE_ALL_COMMANDS_BIT;
    dstAccess = VK_ACCESS_MEMORY_READ_BIT;

Since this memory barrier is performed implicity, you do not need the barrier to use the image inside a commandBuffer.
However, you still need to transition your image from the LAYOUT_PREINITIALIZED to the LAYOUT_TRANSFER_SRC.
Since the execution barrier was done as we saw above, we do not need an another, but we still need an image memory barrier to transition the image. I will do it like that /

    oldLayout = PREINITIALIZED;
    newLayout = TRANSFER_SRC;
    srcStage = TOP_OF_PIPE; // Since it could be 
    srcAccess = 0; 
    dstStage = TRANSFER;
    dstAccess = VK_ACCESS_TRANSFER_READ_BIT; // Since you can use this "cache" before, it is better to make memory visible IMHO

Put `srcAccess` to 0 will lead to validation layer warning. I post an issu [here](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1141)

For the image with memory that resides on GPU side (you called it textureImage I think), you can do:

    oldLayout = UNDEFINED; // obvious
    newLayout = TRANSFER_DST;
    srcStage = TOP_OF_PIPE;
    srcAccess = 0;
    dstStage = TRANSFER;
    dstAccess = 0; // TRANSFER_WRITE is not useful IMHO since you do not need memory visibility

After, you can make the copy !

After the copy is done, you must transition the textureImage's layout to SHADER_READ_ONLY_OPTIMAL;
When the transfer is done? After TRANSFER stage
Before which stage it must be done? Before the FRAGMENT_SHADER (if you use it only in the fragment shader), but I'd go for ALL_GRAPHICS or ALL_COMMANDS (to use it in the computeShader).

So the barrier should be something like that :

    oldLayout = TRANSFER_DST;
    newLayout = SHADER_READ_ONLY;
    srcStage = TRANSFER;
    srcAccess = TRANSFER_WRITE; // Make the memory available
    dstStage = ALL_COMMANDS; FRAGMENT_SHADER; // It is up to you;
    dstAccess = SHADER_READ; // Make the memory visible for shader reads !

It is where I think you must correct it.

IMHO you must as well use barrier when you use buffers ! But in my opinion you just need one and only one barrier for buffers (to make the memory visible after the transfer :))

IMHO, TOP_OF_PIPE for barrier is not a good idea.
I tryed to make that clear on my [website](http://cpp-rendering.io/barriers-vulkan-not-difficult).

I hope I did not forget anything.

**Comment by Overv** [comment]
With regards to your global barrier, it may be preferable to keep the old code to be explicit about the intend, but note that it is not actually necessary. Do you agree?

**Comment by qnope** [comment]
I disagree for this transition :
`transitionImageLayout(textureImage, VK_FORMAT_R8G8B8A8_UNORM, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);`

You want to transition the image from TRANSFER_DST to SHADER_READ.
As I wrote above, you must wait the transfer stage to be finished. And you want to use it at the Fragment Shader stage.
That's said, you must flush the caches used for transfers with VK_ACCESS_TRANSFER_WRITE and invalidate caches red by the FRAGMENT_SHADER using VK_ACCESS_SHADER_READ.

So, if you do not want use a "all blocking barrier", you should, IMHO, at least use :

    srcStage = TRANSFER;
    dstStage = FRAGMENT_SHADER
    srcAccess = TRANSFER_WRITE;
    dstAccess = SHADER_READ;

**Comment by qnope** [comment]
Actually, for the dstStage/Access, a TOP_OF_PIPE / 0 should be correct.

**Comment by Overv** [comment]
For your first proposal, am I understanding correctly that you want to change

    if (oldLayout == VK_IMAGE_LAYOUT_PREINITIALIZED && newLayout == VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL) {
        barrier.srcAccessMask = VK_ACCESS_HOST_WRITE_BIT;
        barrier.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
    } else if (oldLayout == VK_IMAGE_LAYOUT_PREINITIALIZED && newLayout == VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL) {
        barrier.srcAccessMask = VK_ACCESS_HOST_WRITE_BIT;
        barrier.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    }

To:

    if (oldLayout == VK_IMAGE_LAYOUT_PREINITIALIZED && newLayout == VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL) {
        barrier.srcAccessMask = 0;
        barrier.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
    } else if (oldLayout == VK_IMAGE_LAYOUT_PREINITIALIZED && newLayout == VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL) {
        barrier.srcAccessMask = 0;
        barrier.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    }

Because if I do this, I still get a warning from the validation layers despite your pull request.

**Comment by qnope** [comment]
It is correct, try to upgrade your validation layer, I pushed a fix that correct this bug : 
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/1142

**Comment by Overv** [comment]
I am aware, but I'm already using the latest version.

**Comment by qnope** [comment]
I do not have any problem
I am using archlinux and use vulkan-extra-layers 1.0.37

**Comment by qnope** [comment]
Here is the code I am using : 
`vk::ImageMemoryBarrier Transferer::transitionImage(Image image,
                                                   vk::ImageLayout oldLayout,
                                                   vk::ImageLayout newLayout,
                                                   vk::ImageSubresourceRange imageSubResourceRange) {
    vk::AccessFlags src, dst;

    if(oldLayout == vk::ImageLayout::eUndefined || oldLayout == vk::ImageLayout::ePreinitialized)
        src = vk::AccessFlags();

    // If it was in transferDst, we wait for transferWrite
    else if(oldLayout == vk::ImageLayout::eTransferDstOptimal)
        src = vk::AccessFlagBits::eTransferWrite;

    // If it was in transferSrc, we wait for transferRead
    else if(oldLayout == vk::ImageLayout::eTransferSrcOptimal)
        src = vk::AccessFlagBits::eTransferRead; // Useless since make available a read is meaningless

    else
        assert(!"This oldLayout is not managed");

    // If it will be transferSrcOptimal, it should be ready at transferRead
    if(newLayout == vk::ImageLayout::eTransferSrcOptimal)
        dst = vk::AccessFlagBits::eTransferRead;

    // If it will be transferDstOptimal
    else if(newLayout == vk::ImageLayout::eTransferDstOptimal)
        dst = vk::AccessFlagBits::eTransferWrite; // Myst be useless since invalidate for a write

    // If it will be shaderReadOnlyOptimal, it should be ready at shaderRead
    else if(newLayout == vk::ImageLayout::eShaderReadOnlyOptimal)
        dst = vk::AccessFlagBits::eShaderRead;

    else
        assert(!"This newLayout is not managed");

    return vk::ImageMemoryBarrier(src, dst, oldLayout, newLayout, VK_QUEUE_FAMILY_IGNORED, VK_QUEUE_FAMILY_IGNORED,
                                  image, imageSubResourceRange);
}`

**Comment by Overv** [comment]
I'm also using version 1.0.37 of the validation layers, although I don't know what "vulkan-extra-layers" is.

**Comment by qnope** [comment]
I guess it is for other validation layers, but 1.0.37 should be good.
What is the message that is gave by the validation layers?

**Comment by Overv** [comment]
`Source AccessMask 0 [None] must have required access bit 16384 [VK_ACCESS_HOST_WRITE_BIT]  when layout is VK_IMAGE_LAYOUT_PREINITIALIZED, unless the app has previously added a barrier for this transition.`

**Comment by qnope** [comment]
It is weird ^^, I do not have any problem... Try to compile by yourself the validation layers? Else, try to compile my VulkanExample Scene and launch it to see if in your case you have the same error or not.

**Comment by Overv** [comment]
Ah, I had a configuration error that caused it to use DLLs from an older SDK. It runs without errors now, I'll update the tutorial.
