### ISSUE TITLE
updateUniformBuffer has incorrect parameter and is inconsistent with the sample code

### ISSUE THREAD

**Issue by bobby3605** [Overv/VulkanTutorial#290]
On the page,
https://vulkan-tutorial.com/Uniform_buffers/Descriptor_layout_and_buffer
it says to use updateUniformBuffer(imageIndex); in the drawFrame() function.
It should be updateUniformBuffer(currentFrame);
Using imageIndex results in a crash because the imageIndex is set by the number of swapchain images, which is not always equal to MAX_FRAMES_IN_FLIGHT.
The sample code correctly uses currentFrame, but the website is different.

**Comment by Overv** [comment]
This has been fixed in cbf32cc2909decb3a94857345c9377b1c2ffb45b after it was also reported in a [comment](http://disq.us/p/2oy8vrz).
