### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by zukas** [Overv/VulkanTutorial#31]
There is a problem on your website https://vulkan-tutorial.com/ where some pages have problem with resource loading and fails to present properly. The following errors are caused by:

    
    <script src="//vulkan-tutorial.com/Uniform_buffers/themes/daux/js/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

The script fails to load and the function call prevents the pages to load as expected.

**Comment by Overv** [comment]
You're right, looking into it now.

**Comment by Overv** [comment]
The problem has been solved, it was a PHP configuration error. Thanks for reporting it.
