### ISSUE TITLE
VDeleter is confusing and unnecessary.

### ISSUE THREAD

**Issue by thomastjeffery** [Overv/VulkanTutorial#32]
While it is good practice to abstract away memory management like this, the VDeleter template class is a completely distinct concept from Vulkan. This tutorial series would be much easier to follow if memory management was explicitly done, not abstracted away.

## The Problem
The code exists to be read, and understood, not elegant and functional. This is a case where elegance hides the functionality.

The reader is here to learn about the Vulkan API, and *nothing else*.
By encapsulating the memory management, the reader has an unnecessary knowledge dependency. He or she must **drop everything, and learn how this new template class works** and *will be used in the future* before they can **do what they came for:** *learn Vulkan.*

To make matters worse, if the reader wants to **use their own abstraction** for memory management, **they still have to figure out what VDeleter is doing** in every subsequent tutorial.

## A Better Way
Don't abstract away any memory management.

### But isn't that bad programming?
Yes.
It is also good teaching.

### Won't I be adding more confusion?
No.
More code does not equate to more confusing code.
Vulkan is inherently verbose. The reader **is expecting to write a lot of code.**

### Won't the reader just make their own VDeleter (or something similar)?
Almost definitely.
Make a separate tutorial about it! That would be a helpful resource to anyone who hasn't already done something similar. Like I said before, 

> The reader is here to learn about the Vulkan API.

Common **abstractions for handling memory are great to know**, but they aren't Vulkan.

**Comment by Overv** [comment]
Yes, the `VDeleter` construct has been fairly controversial. On the other hand, I've also gotten feedback to use NVIDIA's wrapper because "everyone is using that anyway".

I've been thinking about it for a while and I agree with you that the `VDeleter` should be removed from the tutorial. I've previously made changes or rejected changes because they would affect the code's explicitness, which is one of the greatest values offered by Vulkan, but `VDeleter` is still sticking out like a sore thumb.

It's going to take a bit of work to remove it, but I'll try to find time to do it as soon as possible.

**Comment by salamanderrake** [comment]
I don't know why you didn't just use c++11's built in smart pointers, thats what they are there for. Also will you rewrite this to use Vulkan's C++ implemented header?

**Comment by Overv** [comment]
@salamanderrake I would have used C++11's smart pointers if it was actually possible.

**Comment by Overv** [comment]
Here is my current proposal for the second to last chapter without VDeleter:

https://gist.github.com/Overv/8ae9dc53d1bb013ae3781ce3c654c276

I originally wanted to have `cleanup()` and `swapChainCleanup()` functions, but unfortunately the swap chain recreation requires the swap chain to stay alive while the new one is being created. Therefore I've embedded the cleanup calls for swap chain recreation in all of the resource creation functions themselves. What do you think is the best approach for the cleaning up code?

**Comment by Overv** [comment]
The VDeleter concept has now been completely removed from the tutorial and replaced by manual resource management with explicit lifetimes.

**Comment by AdenFlorian** [comment]
I was confused until I found this issue, I've been reading it all day then all of a sudden the VDeleter was gone...

**Comment by Overv** [comment]
@AdenFlorian I'm sorry for the confusion this has caused. You can continue to use the VDeleter by basically wrapping all variables in it, or switch your current code to manual management.
