### ISSUE TITLE
Rename master to main?

### ISSUE THREAD

**Issue by SaschaWillems** [Overv/VulkanTutorial#321]
At Khronos we are currently switching terms from master to main in our repos as per Github's new community practice for respectful naming.

Would it be possible to also do that for this repo? [Github has a tool](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) to simplify this process.

**Comment by saccharineboi** [comment]
Yes, I'd like to have a false sense of self-righteousness too.

**Comment by Overv** [comment]
I don't really have an opinion about this, but sure, why not.
