### ISSUE TITLE
pdf at introduction->ebook is out of date

### ISSUE THREAD

**Issue by d3rp** [Overv/VulkanTutorial#325]
The link on https://vulkan-tutorial.com/Introduction#page_E-book leads to a pdf-file generated in April 2022. Apparently quite a few changes have happened since then (multiple command buffers, handling resize, etc). It was a surprise to switch in mid-tutorial to the web version and notice that it's not entirely compatible with the pdf.

This tutorial is quite amazing. Good work! I've tried my hands on opengl and macos-metal previously, and, though Vulkan is a lot more verbose and explicit, the tutorial (and of course the documentation and validation layers) gives a much better development experience so far.

**Comment by Hjaltesorgenfrei** [comment]
Maybe a Github action should be setup which generates a pdf and creates a release with it?
Then E-book link can just point to the newest release's pdf instead of being contained in the Repo.

**Comment by Overv** [comment]
I will consider setting up some kind of automation after #326.
