### ISSUE TITLE
Generated ebook files have moved to git lfs

### ISSUE THREAD

**Issue by Overv** [Overv/VulkanTutorial#327]
After merging #326 I rewrote the history of the repo to remove all generated PDF/EPUB files from it and re-added them in the latest commit using git lfs. The purpose of this is to fix the size of the repo while keeping the files in a place that is easy to access. I may add a GitHub action to generate these files automatically at some point in the future, but at least it's not as much of a problem to update them very often anymore.

However, as a result of the history rewrite I did have to force push the `main` branch with all-new commits and this will have created conflicts for all open pull requests and other branches people may have been working on. I don't expect this to cause many problems because the current open PRs look semi-dead and any branches that may need to be merged in the future can be updated to merge to the "new" `main`.

If there are any concerns with this change then let me know. I created a backup of the repo before force pushing it, so I can restore it if needed.

**Comment by H-G-Hristov** [comment]
The links in the README.md don't work:
![Screenshot 2023-03-09 at 9 00 26](https://user-images.githubusercontent.com/47526411/223945129-02473c68-7325-4c62-8190-9588e8372564.png)

**Comment by Overv** [comment]
@H-G-Hristov Fixed, sorry for that.

**Comment by Hjaltesorgenfrei** [comment]
I have workflow at https://github.com/Hjaltesorgenfrei/VulkanTutorial/blob/main/.github/workflows/build_and_release_ebook.yml which creates a release on pushes to main, would that be of interest?
