### ISSUE TITLE
Hyperlink to computer graphics book broken

### ISSUE THREAD

**Issue by denis-kralj** [Overv/VulkanTutorial#34]
The link on  `VulkanTutorial/00_Introduction.md` in the second to last paragraph of the About section is broken.

**Comment by Overv** [comment]
What do you mean when you say "broken"?

**Comment by denis-kralj** [comment]
Getting a server not found error when trying to navigate to the page.

**Comment by Overv** [comment]
Interesting, I can reproduce your problem on my VPS but not on my PC at home. Here's an alternate link to the book:

https://www.docdroid.net/UKocmTz/arcsynthesis.pdf.html

**Comment by denis-kralj** [comment]
Hmm, might be a browser cache issue. Try accessing it in incognito mode. However you put it i can change the link to the one you posted here.

**Comment by Overv** [comment]
I've notified the owner of the website, but I think it is a good idea to change the link to the PDF for now. I can change it, but feel free to make a pull request.

**Comment by salamanderrake** [comment]
Why was the old broken link put back?

**Comment by denis-kralj** [comment]
> 
> 
> Why was the old broken link put back?

seems commit b4e45c98d14af003bceabcc9a5b54fc914ca0d71, I'm guessing the owned of the original site put the resource back up. Both links work.

**Comment by salamanderrake** [comment]
They don't work for me, I continually get a connection refuse error when going to the site.

**Comment by salamanderrake** [comment]
Here is abetter link, https://paroj.github.io/gltut/

**Comment by salamanderrake** [comment]
He has a repo https://github.com/paroj/gltut

**Comment by Overv** [comment]
@salamanderrake That is not the original link that was put back, the original (http://www.arcsynthesis.org/gltut/) is still down.

paroj does not seem to be the original author of the tutorial, but it does look like a more up-to-date version so I will link that one instead.

**Comment by Overv** [comment]
Sure, but only provided that they teach computer graphics fundamentals as well as the current link.
