### ISSUE TITLE
disqus embedding doesn't play nice with statically generated files (w/ fix)

### ISSUE THREAD

**Issue by tthelin** [Overv/VulkanTutorial#38]
In figuring out how to statically generate the tutorial, I came across several performance issues where the static files are still trying to reach out to the internet, but with a bad assumption that "//" as a URL prefix would always work (it doesn't when protocol is file:) It takes about ~10s for Chrome to give up on trying to resolve the bad URL for each one of these.

The discuss thread is one of them (loading google analytics and the special font are the others, but you can turn those off via config files).

The disqus thread is part of the patch into the daux theme so it's not so simple.

If we put in "local file detection" as part of the disqus loading code we fix the problem as it'll only load when served from a web server

If you want me to make a formal pull request I can, but basically this is the change to fix the issue (it needs to be incorporated into daux.patch though)

```shell
diff --git a/templates/content.php b/templates/content.php
index 82e79cd..03017b7 100644
--- a/templates/content.php
+++ b/templates/content.php
@@ -26,6 +26,7 @@

     <div id="disqus_thread"></div>
     <script>
+    if (document.location.host) {
         var disqus_config = function() {
             var path = location.pathname;
             if (path == '/') path = '/Introduction';
@@ -38,6 +39,7 @@
             s.setAttribute('data-timestamp', +new Date());
             (d.head || d.body).appendChild(s);
         })();
+    }
     </script>
     <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
 </article>
```

**Comment by Overv** [comment]
Thanks, patched it.
