### ISSUE TITLE
Maybe deprecated developement environment install

### ISSUE THREAD

**Issue by GERNOMA** [Overv/VulkanTutorial#382]
For linux in the development environment chapter it says to use the command "sudo apt install vulkan-validationlayers-dev spirv-tools".

I tried it in an ubuntu 24.04 machine and it threw the following error:

"
Package vulkan-validationlayers-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  vulkan-utility-libraries-dev

E: Package 'vulkan-validationlayers-dev' has no installation candidate
" 

What ended up working in my case was to install "vulkan-validationlayers" without "-dev".

**Comment by Overv** [comment]
Fixed, thanks.
