### ISSUE TITLE
OpenGL version support

### ISSUE THREAD

**Issue by NicolBolas** [Overv/VulkanTutorial#4]
Your website claims that only cards that support OpenGL 4.3 or later will be supported by Vulkan. But I recall that the presentations claimed that OpenGL 4.1 hardware would be the minimum.

**Comment by Overv** [comment]
The website doesn't explicitly state that hardware that doesn't support OpenGL 4.3 can't support Vulkan, just that OpenGL 4.3 hardware *definitely* will. I don't recall the source, but I heard or read somewhere that all OpenGL ES 3.1 hardware can support Vulkan, which is what "OpenGL 4.3" is derived from.

I'll try to find a source for a more specific desktop version.

**Comment by Overv** [comment]
OpenGL 4.1 is mentioned explicitly [here](https://www.khronos.org/message_boards/showthread.php/9717-Will-Vulkan-effectively-quot-replace-quot-OpenGL-or-not). The poster seems trustworthy enough and it's also mentioned in some other places, so I'll change the website.
