### ISSUE TITLE
link to vkCreateDebugReportCallbackEXT is broken

### ISSUE THREAD

**Issue by theyy29** [Overv/VulkanTutorial#42]
On https://vulkan-tutorial.com/Drawing_a_triangle/Setup/Validation_layers, the link for vkCreateDebugReportCallbackEXT to the Khronos documentation results in a 404.

It tries to point to https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkCreateDebugReportCallbackEXT.html

I dont see any *EXT documentation in the file listing there, and correspondingly, it seems that all *EXT links are broken.

**Comment by Overv** [comment]
Yeah, I think this will be a WONTFIX until these extension functions (that almost everyone is using) are added to the Khronos website.
