### ISSUE TITLE
Staging image update

### ISSUE THREAD

**Issue by realitix** [Overv/VulkanTutorial#44]
Hello @Overv,
Thanks for the great tutorial.

I noticed a point that could be improved.
In @SaschaWillems examples, the staging image is a staging buffer, I then asked the question on ##vulkan (irc) and @baldurk (creator of renderdoc) answered to me:

> staging VkBuffers are the way to go. You can use your own packing/padding layout (so you can memcpy directly from a file for example) as you don't have to respect the implementation's image layout, and most image formats won't allow you to create a linear image anyway

His explanation is very good, it would be great to update the tutorial and to use a staging buffer.
What do you think about that ?

**Comment by SaschaWillems** [comment]
I can second that. I've been using linear images for staging at first too, and while that may be fine for basic stuff you'll run into different problems sooner or later and you also have to check for actual linear format compatibility.

Using buffer copies make things a lot easier (and less implementation dependent) and e.g. allow you to directly upload image data from libraries like gli.

**Comment by Overv** [comment]
I agree, although this will take some time because I have to rewrite the whole "Images" chapter. I think I'm going to remove the `VDeleter` first.

**Comment by Overv** [comment]
The texture mapping has now been updated to use a staging buffer rather than a staging image.

https://vulkan-tutorial.com/Texture_mapping/Images
