### ISSUE TITLE
CMake in Development Environment Section

### ISSUE THREAD

**Issue by AustinHaugerud** [Overv/VulkanTutorial#53]
I think it would be worth while putting CMake in place of Make for this section.  If your version of CMake isn't too old (at least 3.7) CMake already comes with a module FindVulkan.cmake. Creating a CMake project can then look pretty simple.

```
cmake_minimum_required(VERSION 3.7)
project(vulkan_tut)

set(CMAKE_CXX_STANDARD 14)

set(SOURCE_FILES main.cpp)
add_executable(vulkan_tut ${SOURCE_FILES})

find_package(PkgConfig REQUIRED)

pkg_search_module(GLFW REQUIRED glfw3)

include_directories(${GLFW_INCLUDE_DIRS})

find_package(Vulkan REQUIRED)

find_package(glm REQUIRED)

target_link_libraries(vulkan_tut ${GLFW_LIBRARIES} ${Vulkan_LIBRARIES})
```
If you're for some reason stuck with an old version of CMake, glfw3 actually comes with its own FindVulkan.cmake.

**Comment by Overv** [comment]
I don't have a lot of experience with CMake myself, so could you perhaps modify the development environment sections for Linux (and perhaps also Windows) to describe this setup?

**Comment by AustinHaugerud** [comment]
Sure, I'm not sure how your contribution process works, but I don't believe it'd take much work to adjust things. For the Windows section adding CMake could be a good idea, but I wouldn't remove the Visual Studio process. I'd imagine a lot of Windows developers don't use CMake since VS is all they use. For cross platform developers, or even just people who want to support another IDE other than VS, it can be nice.

**Comment by Overv** [comment]
Yes, I agree. We should replace the makefile section with CMake and refer Windows users who would like to use CMake to that section. If you can fork the repo and rewrite that section with appropriate cmake instructions that are also suitable for new users, then I will review it and merge it.

**Comment by AustinHaugerud** [comment]
Alright, I'll let you know when I'm ready for you to review a fork!
