### ISSUE TITLE
Code left over from saving result in 03/00/01 (creating two instances)

### ISSUE THREAD

**Issue by vikhik** [Overv/VulkanTutorial#54]
In the [tutorial noted](https://github.com/Overv/VulkanTutorial/blob/master/03_Drawing_a_triangle/00_Setup/01_Instance.md), we create the instance and store the result in one line of code:

`VkResult result = vkCreateInstance(&createInfo, nullptr, &instance);`

And then immediately ignore the result (apparently this is the new preferred method?) and create the instance again:

`if (vkCreateInstance(&createInfo, nullptr, &instance) != VK_SUCCESS) {`

I assume that either the first part should no longer exist, or the second part should revert to `if (result != VK_SUCCESS) {`

**Comment by Overv** [comment]
I realise that it's not entirely clear, but you are supposed to replace the first line with the new code.

**Comment by vikhik** [comment]
This line here could be tweaked to showcase that:
"To check if the instance was created successfully, simply **add** a check for the success value:"
->
"To check if the instance was created successfully, we don't need to store the result, and can just use a check for the success value instead:"

**Comment by Overv** [comment]
Fixed.
