### ISSUE TITLE
transitionImageLayout function doesn't follow the spec

### ISSUE THREAD

**Issue by vazgriz** [Overv/VulkanTutorial#60]
The table in Section 6.1.3, specifies what pipeline stage each access mask can be accessed in. For example, when `dstAccessMask` is `VK_ACCESS_TRANSFER_WRITE_BIT`, `dstStageMask` must be `VK_PIPELINE_STAGE_TRANSFER_BIT`. The current function always uses `VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT` for the source and dest stage.

The easiest way to correct this would be choosing the source and dest stages alongside the access masks

```
VkPipelineStageFlags source;
VkPipelineStageFlags dest;

if (oldLayout == VK_IMAGE_LAYOUT_UNDEFINED && newLayout == VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL) {
    barrier.srcAccessMask = 0;
    barrier.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;

    source = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
    dest = VK_PIPELINE_STAGE_TRANSFER_BIT;
}

...

vkCmdPipelineBarrier(
    commandBuffer,
    source, dest,
    0,
    0, nullptr,
    0, nullptr,
    1, &barrier
);
```

**Comment by Overv** [comment]
Good catch, I wasn't aware of that limitation. I will update the tutorial tomorrow or the day after to include this in the tutorial explanation and `transitionImageLayout`.
