### ISSUE TITLE
"failed to create swap chain" when collapse window

### ISSUE THREAD

**Issue by Mikez2015** [Overv/VulkanTutorial#69]
All samples after "re-creation surface" have this bug.
If collapse  window - programm terminated with error "failed to create swap chain"

Windows 7x64, VS 2017

**Comment by SaschaWillems** [comment]
If you're on nvidia hardware then you're running into a bug with current drivers. This happens on my setup with my samples too. I did report this some time ago to nvidia but it seems they still haven't fixed it yet.

**Comment by Overv** [comment]
Although this is a driver peculiarity, I have changed the code in the tutorial to avoid recreating the swap chain in the case where the window size is `0, 0`.
