### ISSUE TITLE
Provide utility for building the code

### ISSUE THREAD

**Issue by rtbo** [Overv/VulkanTutorial#70]
There are dozens of cpp file under the code directory.
I might have missed something, but I can't find any support for building them into executables.
I've seen the Development Environment chapter, but I think this is missing actual ready to go build scripts.

**Comment by Overv** [comment]
I have not included ready to go build scripts because the code is not really supposed to be used apart from the tutorial. Why would you want build scripts in the repository itself?

**Comment by rtbo** [comment]
I was skimming the surface of the tuto and wanted to have a quick view on the results of the code.
I recognize it is not a high priority and not something most readers would need. After all the goal is to get our hands dirty and there are others samples collections available for that purpose.

I have read the tuto in greater details by the time. It's the best available IMO. Pedagogy is really smooth for such a complex topic.
