### ISSUE TITLE
Validation layers

### ISSUE THREAD

**Issue by johnfg10** [Overv/VulkanTutorial#73]
Hey,
Great tutorial! but i just wanted to check 
![image](https://user-images.githubusercontent.com/5445550/38174350-f80f1154-35c3-11e8-8d31-2a4c4ca8a746.png)
Im not getting this error which im presuming is incorrect? ive put my version on gist here: **https://gist.github.com/johnfg10/41d31da51db2a6c7f2aca0f7c10ac7ea**
thanks in advance,
John

**Comment by Overv** [comment]
I do get the message when using your code. Are you sure that you are running your program in debug mode and you keep the command prompt open by running it with Ctrl+F5 (if using Visual Studio) or by running it in a separate terminal?

**Comment by LJXLJXLJX** [comment]
I run your code and get message like this

> validation layer:  [ VUID-vkDestroyInstance-instance-00629 ] Object: 0x2aefa40000000001 (Type = 28) | OBJ ERROR : For VkInstance 0x1c63a922820[], VkDebugReportCallbackEXT 0x2aefa40000000001[] has not been destroyed. The Vulkan spec states: All child objects created using instance must have been destroyed prior to destroying instance (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroyInstance-instance-00629)

Anyone know what's wrong?
