### ISSUE TITLE
vkQueueWaitIdle only when validation layers are enabled

### ISSUE THREAD

**Issue by meh2481** [Overv/VulkanTutorial#76]
https://github.com/Overv/VulkanTutorial/blob/343c0a0731d83bcf3b526361a2ecee70becd81a6/code/15_hello_triangle.cpp#L647

Should be wrapped in an `if(enableValidationLayers)` check, as the memory leak is only present when validation layers are enabled.

(Also affects other examples after this one)

**Comment by Overv** [comment]
That's a good idea, also adds to the self-documenting code factor.
