### ISSUE TITLE
Redesign drawing and presentation logic

### ISSUE THREAD

**Issue by Overv** [Overv/VulkanTutorial#81]
There are two known issues in the current drawing and presentation logic of the tutorial:

1. Rendering of frames spirals out of control because semaphores are not used properly and there is no host<->GPU synchronization. (#77 #76 #22)
2. It is unclear if subpass dependencies are used properly, especially with regards to the depth buffer and memory reads as part of presentation.

I will research other samples and reference code to correct these and update the tutorial + code.

**Comment by Overv** [comment]
Just to give an update on this, I've written an updated version of the rendering and presentation sample code and will be updating that chapter itself this week.

**Comment by Overv** [comment]
The tutorial has now been updated.

**Comment by Carlbaum** [comment]
@Overv Thanks for the great tutorials! I'm currently working my way through them and just suspected that some changes had been made (which led me to this page).

Just a thought: It'd be great if you could add some notification to the tutorials when you update them  (maybe you already have but I missed it?). It'd be nice to see something like what, why and when changes were made.

**Comment by Overv** [comment]
@Carlbaum I used to have a mailing list to keep people up-to-date on the website, but I think that right now being a watcher on the repository is the best way to be notified. However, in general changes as large as this one are very rare.
