### ISSUE TITLE
Chapter on multisampling

### ISSUE THREAD

**Issue by kondrak** [Overv/VulkanTutorial#99]
I feel that one thing that's still missing from the tutorial to make it complete is a chapter on how to implement multisampling in existing code. Given that the reader made it past mipmapping, adding multisampling won't be that difficult and as of today it's basically a minimum feature to have in a renderer/game engine.

What do you think? If it sounds interesting (and nobody else is working on it to your knowledge) I'd be happy to contribute.

**Comment by Overv** [comment]
Hey,

I definitely agree that it would be nice to have a chapter on multisampling (and one on compute shaders at some point). I've wanted to add chapters like that for some time but unfortunately haven't really had the time for it. I'm not aware of anyone else planning to contribute a multisampling chapter either.

If you are willing to write one then I'd be happy to support you in your effort as much as possible. Do you have ideas for a rough outline of what the chapter would look like?

**Comment by kondrak** [comment]
A rough sketch of the chapter would be similar what's already out there on vulkan-tutorial to maintain consistency, so for example:
- explanation of what multisampling is and why we want it demonstrated with a picture
- modification of existing code to accomodate for multisampling

So keeping it simple.

**Comment by kondrak** [comment]
Sounds about the same way I wanted to approach this, I'll post a PR as soon as I have something done :-)
